var po_LangOrder = {ru: 0};
var po_Translate = {"Cyborg Factory":["Завод киборгов"],
"Reinforced Base Structure Materials":["Улучшенные стройматериалы"],
"Fuel Injection Engine":["Инжекторный двигатель"],
"Wheeled Propulsion":["Двигатель - колеса"],
"Dedicated Synaptic Link Data Analysis":["Углублённый анализ синаптической связи"],
"Hardened Base Structure Materials":["Укреплённые стройматериалы"],
"Automated VTOL Rearming":["Автоматизированная перезарядка ВВС"],
"Turbo-Charged Engine":["Двигатель с турбонаддувом"],
"Neural Synapse Research Brain":["Исследование нейросинапса"],
"Advanced Base Structure Materials":["Продвинутые стройматериалы"],
"Robotic VTOL Rearming":["Роботоперевооружение ВВС"],
"Gas Turbine Engine":["Газотурбинный двигатель"],
"New Design":["Новый дизайн"],
"Truck":["Грузовик"],
"Machinegun Viper Wheels":["Пулемёт Гадюка Колёса"],
"Light Cannon Viper Wheels":["Легкая пушка Гадюка Колеса"],
"Flamer Viper Wheels":["Огнемет Гадюка Колёса"],
"Sensor Turret Viper Wheels":["Датчик Гадюка Колёса"],
"Light Cannon Viper Tracks":["Легкая пушка Гадюка Гусеницы"],
"Heavy Machinegun Cobra Half-tracks":["Тяжелый пулемёт Кобра Полугусеницы"],
"Mortar Cobra Half-tracks":["Миномёт Кобра Полугусеницы"],
"Light Cannon Cobra Tracks":["Легкая пушка Кобра Гусеницы"],
"Medium Cannon Viper Tracks":["Средняя пушка Гадюка Гусеницы"],
"Repair Turret Viper Wheels":["Ремонтная Гадюка Колёса"],
"Twin Machinegun Viper Wheels":["Двойной пулемёт Гадюка Колёса"],
"Twin Machinegun Viper Half-tracks":["Двойной пулемёт Гадюка Полугусеницы"],
"Heavy Machinegun Viper Half-tracks":["Тяжелый пулемёт Гадюка Полугусеницы"],
"Heavy Machinegun Viper Tracks":["Тяжелый пулемет Гадюка Гусеницы"],
"Lancer Viper Wheels":["Лансер Гадюка Колёса"],
"Mini-Rocket Viper Wheels":["Миниракеты Гадюка Колёса"],
"Medium Cannon Cobra Tracks":["Средняя пушка Кобра Гусеницы"],
"Heavy Cannon Cobra Tracks":["Тяжелая пушка Кобра Гусеницы"],
"Cobra Truck":["Кобра Грузовик"],
"Flamer Cobra Tracks":["Огнемёт Кобра Гусеницы"],
"Bombard Cobra Half-tracks":["Бомбард Кобра Полугусеницы"],
"Command Turret Cobra Half-tracks":["Командная Кобра Полугусеницы"],
"Lancer Cobra Half-tracks":["Лансер Кобра Полугусеницы"],
"Light Cannon Python Tracks":["Легкая пушка Гадюка полугусеницы"],
"Medium Cannon Python Tracks":["Средняя пушка Питон Гусеницы"],
"Heavy Cannon Python Tracks":["Тяжелая пушка Питон Гусеницы"],
"Command Turret Python Tracks":["Командная Питон Гусеницы"],
"Scavenger":["Мусорщик"],
"Jeep":["Джип"],
"Trike":["Мотоцикл"],
"Buggy":["Багги"],
"Rocket Buggy":["Ракетный багги"],
"Rocket Jeep":["Ракетный джип"],
"Fire Truck":["Пожарная машина"],
"Pick-Up Truck":["Транспортный грузовик"],
"Cannon Fire Truck":["Пожарная машина с пушкой"],
"School Bus":["Школьный автобус"],
"Civilian":["Гражданский"],
"Machinegunner":["Пулеметчик"],
"Flamer":["Огнемёт"],
"Lancer":["Лансер"],
"Heavy Gunner":["Тяжелый артиллерист"],
"Cyborg Flamer":["Огнеметчик"],
"Assault Gunner":["Штурмовик"],
"Cyborg Cannon":["Артиллерист"],
"Viper":["Гадюка"],
"Leopard":["Леопард"],
"Retaliation":["Возмездие"],
"Bug":["Жук"],
"Cobra":["Кобра"],
"Panther":["Пантера"],
"Retribution":["Кара"],
"Scorpion":["Скорпион"],
"Tiger":["Тигр"],
"Vengeance":["Месть"],
"Python":["Питон"],
"Mantis":["Богомол"],
"Transport Body":["Корпус транспорта"],
"Command Turret":["Командная туррель"],
"Demolish":["Снести"],
"Wheels":["Колёса"],
"Wheels II":["Колёса II"],
"Wheels III":["Колёсах III"],
"Tracks":["Гусеницы"],
"Tracks II":["Гусеницы II"],
"Tracks III":["Гусеницы III"],
"Hover":["Ховер"],
"Hover II":["Ховер II"],
"Hover III":["Ховер III"],
"VTOL":["ВВС"],
"VTOL II":["ВВС II"],
"VTOL III":["ВВС III"],
"Half-tracks":["Полугусеницы"],
"Half-tracks II":["Полугусеницы II"],
"Half-tracks III":["Полугусеницы III"],
"Cyborg Propulsion II":["Кибердвижитель II"],
"Cyborg Propulsion III":["Кибердвижитель III"],
"Naval":["ВМС"],
"Cyborg Propulsion":["Кибердвижитель"],
"Repair Turret":["Ремонтная башня"],
"Sensor Tower":["Сенсорная башня"],
"Hardened Sensor Tower":["Укреплённая сенсорная башня"],
"Sensor Turret":["Башня с датчиком"],
"VTOL CB Radar Tower":["Башня ВВС КБ"],
"Uplink Sensor":["Датчик связи"],
"CB Radar Turret":["Башня КБ радара"],
"VTOL Strike Turret":["Боевая башня ВВС"],
"VTOL CB Radar Turret":["Башня ВВС КБ"],
"Oil Derrick":["Нефтяная вышка"],
"Command Center":["Командный центр"],
"Factory":["Завод"],
"Factory Module":["Заводской модуль"],
"Power Generator":["Генератор энергии"],
"Power Module":["Энегертический блок"],
"Research Facility":["Исследовательская лаборатория"],
"Research Module":["Исследовательский модуль"],
"Demolish Structure":["Снести сооружение"],
"Repair Center":["Ремонтный центр"],
"Command Relay Center":["Командный пост"],
"Hardcrete Corner Wall":["Бетонная угловая стена"],
"Hardcrete Wall":["Бетонная стена"],
"VTOL Factory":["Авиазавод"],
"Inferno Hardpoint":["Укрепленая точка Инферно"],
"Pepperpot Pit":["Пепперпот"],
"Hellstorm Emplacement":["Установка Шторм Ада"],
"Tornado AA Flak Site":["Зенитка Торнадо"],
"Hurricane AA Site":["Зенитка Ураган"],
"Whirlwind AA Site":["Зенитка Вихрь"],
"Ripple Rocket Battery":["Ракетная батарея"],
"Assault Cannon Guard Tower":["Сторожевая вышка со Штурмовой пушкой"],
"Assault Gun Hardpoint":["Укрепленная точка со Штурмовым орудием"],
"Assault Cannon Hardpoint":["Укрепленная точка со Штурмовой пушкой"],
"CB Tower":["КБ Башня"],
"VTOL CB Tower":["Башня ВВС КБ"],
"Heavy Machinegun Hardpoint":["Оборонительная точка с крупнокалиберным пулемётом"],
"Light Cannon Hardpoint":["Оборонительная точка с мелкокалиберной пушкой"],
"Medium Cannon Hardpoint":["Оборонительная точка со среднекалиберной пушкой"],
"Heavy Cannon Hardpoint":["Оборонительная точка с тяжелой пушкой"],
"Flamer Hardpoint":["Оборонительная точка с огнемётом"],
"Lancer Hardpoint":["Укрепленная точка Лансера"],
"Machinegun Guard Tower":["Пулеметная башня"],
"Twin Machinegun Guard Tower":["Башня с двойным пулеметом"],
"Heavy Machinegun Tower":["Башня с тяжелым пулемётом"],
"Flamer Guard Tower":["Башня с огнеметом"],
"Lancer Tower":["Башня Лансера"],
"Mini-Rocket Tower":["Башня миниракет"],
"Machinegun Bunker":["Бункер с пулемётом"],
"Twin Machinegun Bunker":["Бункер со спаренным пулемётом"],
"Heavy Machinegun Bunker":["Бункер с крупнокалиберным пулемётом"],
"Light Cannon Bunker":["Бункер с мелкокалиберной пушкой"],
"Flamer Bunker":["Огнемётный бункер"],
"Lancer Bunker":["Бункер Лансера"],
"Tank Traps":["Танковая ловушка"],
"Dragon's Teeth":["Клыки Дракона"],
"VTOL Rearming Pad":["Посадочная площадка ВВС"],
"Howitzer Emplacement":["Установка гаубицы"],
"Flashlight Emplacement":["Установка вспышки"],
"Rail Gun Hardpoint":["Оборонительная точка с рельсовой пушкой"],
"Scourge Missile Tower":["Башня с ракетой Бич"],
"Needle Gun Tower":["Башня с иглометом"],
"Gauss Cannon Emplacement":["Установка пушки Гаусса"],
"Light Cannon":["Легкая пушка"],
"Medium Cannon":["Средняя пушка"],
"Heavy Cannon":["Тяжелая пушка"],
"Hyper Velocity Cannon":["Гиперскоростная пушка"],
"Assault Cannon":["Штурмовая пушка"],
"Inferno":["Инферно"],
"Howitzer":["Гаубица"],
"Ground Shaker":["Сотрясатель"],
"Ground Shaker Emplacement":["Установка сотрясателя"],
"Hellstorm":["Адский шторм"],
"Pulse Laser":["Импульсный лазер"],
"Machinegun":["Пулемёт"],
"Twin Machinegun":["Спаренный пулемёт"],
"Heavy Machinegun":["Тяжелый пулемёт"],
"Assault Gun":["Штурмовое орудие"],
"Scourge Missile":["Ракета Бич"],
"Vindicator SAM":["Защитник ЗВ"],
"Archangel Missile":["Ракета Архангел"],
"Avenger SAM":["Мститель ЗВ"],
"VTOL Scourge Missile":["Ракета Бич ВВС"],
"Mortar":["Миномёт"],
"Mortar Emplacement":["Установка миномета"],
"Bombard":["Бомбард"],
"Bombard Emplacement":["Установка Бомбарда"],
"Pepperpot":["Пепперпот"],
"Pepperpot Emplacement":["Установка Пепперпот"],
"Needle Gun":["Игломет"],
"Rail Gun":["Рельсовая пушка"],
"Gauss Cannon":["Пушка Гаусса"],
"Bunker Buster":["Антибункер"],
"Mini-Rocket Pod":["Блок миниракет"],
"Ripple Rockets":["Ракеты"],
"Tank Killer":["Танк-Киллер"],
"VTOL Bunker Buster":["ВВС Антибункер"],
"VTOL Mini-Rocket":["Миниракеты ВВС"],
"VTOL Lancer":["ВВС Лансер"],
"VTOL Tank Killer":["ВВС Танк-Киллер"],
"Tornado Flak Turret":["Туррель Торнадо"],
"Whirlwind AA Turret":["Туррель Вихрь"],
"Hurricane AA Turret":["Туррель Ураган"],
"VTOL Cannon":["ВВП Пушка"],
"VTOL Hyper Velocity Cannon":["Авиационная гиперскоростная пушка"],
"VTOL Assault Cannon":["Штурмовая авиапушка"],
"VTOL Pulse Laser":["Авиационный импульсный лазер"],
"VTOL Machinegun":["Авиационный пулемёт"],
"VTOL Twin Machinegun":["Авиационный спаренный пулемёт"],
"VTOL Heavy Machinegun":["Авиационный тяжёлый пулемёт"],
"VTOL Assault Gun":["Авиационное штурмовое орудие"],
"VTOL Needle Gun":["ВВС игломет"],
"VTOL Rail Gun":["Авиационная рельсовая пушка"],
"Proximity Bomb Turret":["Отсек для бомб"],
"Proximity Superbomb Turret":["Отсек для супербомб"],
"VTOL Heap Bomb Bay":["Бронебойные взрывчатые бомбы"],
"VTOL Phosphor Bomb Bay":["Фосфорные бомбы"],
"VTOL Thermite Bomb Bay":["Термитные бомбы"],
"Collective Wall":["Стена Альянса"],
"CAM1 RESEARCH":["КАМП1 Исследования"],
"ADVANCED RESEARCH":["Продвинутое исследование"],
"CAM1 VEHICLES":["КАМП1 Машины"],
"CAM1 WEAPONS":["КАМ1 Оружие"],
"CAM1 SYSTEMS":["КАМ1 Системы"],
"CAM1 DEFENSES":["КАМ1 Защита"],
"CAM1 STRUCTURES":["КАМ1 постройки"],
"CAM2 RESEARCH":["КАМ2 Исследования"],
"CAM2 VEHICLES":["КАМ2 Машины"],
"CAM2 CYBORGS":["КАМ2 Киборги"],
"CAM2 WEAPONS":["КАМ2 Оружие"],
"CAM2 SYSTEMS":["КАМ2 Системы"],
"CAM2 DEFENSES":["КАМ2 Защита"],
"CAM2 STRUCTURES":["КАМ2 Постройки"],
"CAM3 RESEARCH":["КАМ3 Исследования"],
"Synaptic Link":["Синаптическая связь"],
"Missile Targeting Codes":["Коды наведения ракет"],
"Second Level Missile Targeting Codes":["Второй уровень кодов наведения"],
"Third Level Missile Firing Codes":["Третий Уровень - коды запуска ракет"],
"Cyborg Thermal Armor":["Термоброня киборгов"],
"Cyborg Thermal Armor Mk2":["Термоброня киборгов Mk2"],
"Cyborg Thermal Armor Mk3":["Термоброня киборгов Mk3"],
"Cyborg High Intensity Thermal Armor":["Усиленная термоброня киборгов"],
"Cyborg High Intensity Thermal Armor Mk2":["Усиленная термоброня киборгов Mk2"],
"Cyborg High Intensity Thermal Armor Mk3":["Усиленная термоброня киборгов Mk3"],
"Cyborg Composite Alloys":["Композитный сплав киборгов"],
"Cyborg Composite Alloys Mk2":["Композитный сплав киборгов Mk2"],
"Cyborg Composite Alloys Mk3":["Композитный сплав киборгов Mk3"],
"Cyborg Dense Composite Alloys":["Плотный композитный сплав киборгов"],
"Cyborg Dense Composite Alloys Mk2":["Плотный композитный сплав киборгов Mk2"],
"Cyborg Dense Composite Alloys Mk3":["Плотный композитный сплав киборгов Mk3"],
"Cyborg Superdense Composite Alloys":["Сверхплотный композитный сплав киборгов"],
"Cyborg Superdense Composite Alloys Mk2":["Сверхплотный композитный сплав киборгов Mk2"],
"Cyborg Superdense Composite Alloys Mk3":["Сверхплотный композитный сплав киборгов Mk3"],
"Bunker Blaster Cyborg":["Киборг-антибункер"],
"Heavy Gunner Cyborg":["Киборг с тяжелым орудием"],
"Flamer Cyborg":["Огнемётчик"],
"Machinegunner Cyborg":["Пулемётчик"],
"Jump Bunker Blaster":["Прыгун Антибункер"],
"Jump Heavy Gunner":["Прыгун с тяжелым орудием"],
"Jump Lancer":["Прыгун-Лансер"],
"Jump Assault Gunner":["Прыгун-штурмовик"],
"Jump Needle Gunner":["Прыгун-игломётчик"],
"Jump Scourge":["Прыгун Бич"],
"Jump Flashlight Gunner":["Прыгун-вспышка"],
"Cyborg Jump Pack":["Комплект для прыжка киборгов"],
"Hardcrete":["Хардкрит"],
"NP-Hardcrete":["NP-Хардкрит"],
"Improved Hardcrete":["Улучшенный хардкрит"],
"Improved Hardcrete Mk2":["Улучшенный хардкрит Мk2"],
"Improved Hardcrete Mk3":["Улучшенный хардкрит Мk3"],
"Supercrete":["Суперкрит"],
"Supercrete Mk2":["Суперкрит Мk2"],
"Supercrete Mk3":["Суперкрит Мk3"],
"Plascrete":["Пласткрит"],
"Plascrete Mk2":["Пласткрит Мk2"],
"Plascrete Mk3":["Пласткрит МК3"],
"Tank Killer Emplacement":["Установка Танк-Киллера"],
"Bombard Pit":["Бомбардный окоп"],
"Archangel Missile Battery":["Батарея ракет Архангел"],
"Mortar Pit":["Минометный окоп"],
"Mini-Rocket Battery":["Батарея миниракет"],
"Pulse Laser Emplacement":["Установка импульсного лазера"],
"Rail Gun Emplacement":["Установка Рельсовой пушки"],
"Assault Gun Emplacement":["Установка штурмового орудия"],
"Avenger SAM Site":["Позиция Мстителя ЗВ"],
"Vindicator SAM Site":["Позиция Защитника ЗВ"],
"Scourge Missile Hardpoint":["Укрепленная точка с ракетой Бич"],
"Tank Killer Hardpoint":["Укрепточка Танк-Киллера"],
"Gauss Cannon Hardpoint":["Укрепточка с пушкой Гаусса"],
"Command Relay Post":["Командный Пост"],
"Reinforced Base Structure Materials Mk2":["Прочные стройматериалы Мk2"],
"Reinforced Base Structure Materials Mk3":["Прочные стройматериалы Мk3"],
"Hardened Base Structure Materials Mk2":["Усиленные стройматериалы Мk2"],
"Hardened Base Structure Materials Mk3":["Усиленные стройматериалы Мk3"],
"Advanced Base Structure Materials Mk2":["Продвинутые стройматериалы Мk2"],
"Advanced Base Structure Materials Mk3":["Продвинутые стройматериалы Мk3"],
"Gas Turbine Generator":["Газотурбинный генератор"],
"Vapor Turbine Generator":["Паротурбинный генератор"],
"Repair Facility":["Ремонтная мастерская"],
"Automated Repair Facility":["Автоматизированная ремонтная мастрская"],
"Synaptic Link Data Analysis":["Анализ нейросвязи"],
"Synaptic Link Data Analysis Mk2":["Анализ нейросвязи Мk2"],
"Synaptic Link Data Analysis Mk3":["Анализ нейросвязи Мk3"],
"Dedicated Synaptic Link Data Analysis Mk2":["Углубленный анализ нейросвязи Мk2"],
"Dedicated Synaptic Link Data Analysis Mk3":["Углубленный анализ нейросвязи Мk3"],
"Neural Synapse Research Brain Mk2":["Исследование нейросинапса Мk2"],
"Neural Synapse Research Brain Mk3":["Исследование нейросинапса Мk3"],
"Automated VTOL Rearming Mk2":["Автоперевооружение ВВС Мk2"],
"Automated VTOL Rearming Mk3":["Автоперевооружение ВВС Мk3"],
"Robotic VTOL Rearming Mk2":["Роботоперевооружение ВВС Мk2"],
"Robotic VTOL Rearming Mk3":["Роботоперевооружение ВВС Мk3"],
"Robotic VTOL Rearming Mk4":["Роботоперевооружение ВВС Мk4"],
"Cyborg Self-Repair":["Авторемонт киборгов"],
"Automated Cyborg Repair Mk2":["Автоматизированное восстановление киборгов Мk2"],
"Automated Cyborg Repair Mk3":["Автоматизированное восстановление киборгов Мk3"],
"Defenses Self-Repair":["Самовосстановление защиты"],
"Automated Defenses Repair Mk2":["Автоматизированный ремонт защиты Мk2"],
"Automated Defenses Repair Mk3":["Автоматизированный ремонт защиты Мk3"],
"Base Structure Self-Repair":["Самовосстановление построек"],
"Automated Base Structure Repair Mk2":["Автоматизированное восстановление построек Мk2"],
"Automated Base Structure Repair Mk3":["Автоматизированное восстановление построек Мk3"],
"Vehicle Self-Repair":["Самовосстановление машин"],
"Automated Vehicle Repair Mk2":["Автоматизированное самовосстановление машин Мk2"],
"Automated Vehicle Repair Mk3":["Автоматизированное самовосстановление машин Мk3"],
"Sensor Upgrade":["Улучшение датчика"],
"Construction Unit":["Строительный юнит"],
"Engineering":["Техника"],
"Improved Engineering":["Улучшенная техника"],
"Advanced Engineering":["Продвинутая техника"],
"Mobile Repair Turret":["Мобильная ремонтная башня"],
"Mobile Repair Upgrade":["Улучшенная мобильная мастерская"],
"Mobile Repair Upgrade Mk2":["Улучшенная мобильная мастерская МК2"],
"CB Turret":["КБ башня"],
"CB Sensor Upgrade":["Улучшение КБ Башни"],
"CB Sensor Upgrade 2":["Улучшение КБ Башни 2"],
"CB Sensor Upgrade 3":["Улучшение КБ Башни 3"],
"VTOL CB Turret":["Башня ВВС КБ"],
"VTOL CB Upgrade":["Улучшение ВВС КБ Башни"],
"VTOL CB Upgrade 2":["Улучшение ВВС КБ Башни 2"],
"VTOL CB Upgrade 3":["Улучшение ВВС КБ Башни 3"],
"VTOL Strike Upgrade":["Улучшение боевой башни ВВС"],
"VTOL Strike Upgrade Mk2":["Улучшение боевой башни ВВС Мk2"],
"VTOL Strike Upgrade Mk3":["Улучшение боевой башни ВВС Мk3"],
"VTOL Strike Tower":["Бонвая башня ВВС"],
"Improved Scrambler":["Улучшенный шифратор"],
"Scrambler Turret Mk2":["Башня захвата Мk2"],
"Sensor Lock":["Блокировка датчика"],
"Thermal Armor":["Термоброня"],
"Thermal Armor Mk2":["Термоброня Mk2"],
"Thermal Armor Mk3":["Термоброня Mk3"],
"High Intensity Thermal Armor":["Усиленная термоброня"],
"High Intensity Thermal Armor Mk2":["Усиленная термоброня Mk2"],
"High Intensity Thermal Armor Mk3":["Усиленная термоброня Mk3"],
"Light Body - Viper":["Легкая броня - Гадюка"],
"Light Body - Leopard":["Легкая броня - Леопард"],
"Light Body - Retaliation":["Легкая броня - Возмездие"],
"Light Body - Bug":["Легкая броня - Жук"],
"Medium Body - Cobra":["Средняя броня - Кобра"],
"Medium Body - Panther":["Средняя броня - Пантера"],
"Medium Body - Retribution":["Средняя броня - Кара"],
"Medium Body - Scorpion":["Средняя броня - Скорпион"],
"Heavy Body - Tiger":["Тяжелая броня - Тигр"],
"Heavy Body - Vengeance":["Тяжелая броня - Месть"],
"Heavy Body - Python":["Тяжелая броня - Питон"],
"Heavy Body - Mantis":["Тяжелая броня - Богомол"],
"Fuel Injection Engine Mk2":["Инжекторный двигатель Mk2"],
"Fuel Injection Engine Mk3":["Инжекторный двигатель Mk3"],
"Turbo-Charged Engine Mk2":["Двигатель с турбонаддувом Mk2"],
"Turbo-Charged Engine Mk3":["Двигатель с турбонаддувом Mk3"],
"Gas Turbine Engine Mk2":["Газотурбинный двигатель Mk2"],
"Gas Turbine Engine Mk3":["Газотурбинный двигатель Mk3"],
"Composite Alloys":["Композитный сплав"],
"Composite Alloys Mk2":["Композитный сплав Mk2"],
"Composite Alloys Mk3":["Композитный сплав Mk3"],
"Dense Composite Alloys":["Плотный композитный сплав"],
"Dense Composite Alloys Mk2":["Плотный композитный сплав Mk2"],
"Dense Composite Alloys Mk3":["Плотный композитный сплав Mk3"],
"Superdense Composite Alloys":["Сверхплотный композитный сплав"],
"Superdense Composite Alloys Mk2":["Сверхплотный композитный сплав Mk2"],
"Superdense Composite Alloys Mk3":["Сверхплотный композитный сплав Mk3"],
"Hover Propulsion":["Ховер-движитель"],
"Hover Propulsion II":["Ховер-движитель II"],
"Half-tracked Propulsion":["Полугусеницы"],
"Half-tracked Propulsion II":["Полугусеницы II"],
"Tracked Propulsion":["Гусеницы"],
"Tracked Propulsion II":["Гусеницы II"],
"VTOL Propulsion":["ВВС движитель"],
"VTOL Propulsion II":["ВВС движитель II"],
"Wheeled Propulsion II":["Колёсный движитель II"],
"AA Thermal Imaging Sensor":["Тепловой сенсор ПВО"],
"AA Target Acquisition Shells":["Снаряды целевого прогноза ПВО"],
"AA Target Prediction Computer":["Компьютерное целеуказание ПВО"],
"AA HE Flak":["Разрывные патроны для ПВО"],
"AA HE Flak Mk2":["Разрывные патроны для ПВО Мk2"],
"AA HE Flak Mk3":["Разрывные патроны для ПВО Мk3"],
"AA HEAP Flak":["Бронебойная зенитка"],
"AA HEAP Flak Mk2":["Бронебойная зенитка Мk2"],
"AA HEAP Flak Mk3":["Бронебойная зенитка Мk3"],
"AA Ammunition Hopper":["Бункер боеприпасов ПВО"],
"AA Ammunition Hopper Mk2":["Бункер боеприпасов ПВО Мk2"],
"AA Ammunition Hopper Mk3":["Бункер боеприпасов ПВО Мk3"],
"AA Chainfeed Loader":["Цепная подача снарядов ПВО"],
"AA Chainfeed Loader Mk2":["Цепная подача снарядов ПВО Мk2"],
"AA Chainfeed Loader Mk3":["Цепная подача снарядов ПВО Мk3"],
"HEAP Bomb Bay":["Отсек для бронебойных бомб"],
"Phosphor Bomb Bay":["Отчек для фосфорных бомб"],
"Thermite Bomb Bay":["Отсек для термитных бомб"],
"Cannon Laser Rangefinder":["Пушечный лазерный дальномер"],
"Cannon Laser Designator":["Пушечный лазерный целеуказатель"],
"HEAT Cannon Shells":["Противотанковые снаряды"],
"HEAT Cannon Shells Mk2":["Противотанковые снаряды Mk2"],
"HEAT Cannon Shells Mk3":["Противотанковые снаряды Mk3"],
"APFSDS Cannon Rounds":["Подкалиберные снаряды для пушки"],
"APFSDS Cannon Rounds Mk2":["Подкалиберные снаряды для пушки Mk2"],
"APFSDS Cannon Rounds Mk3":["Подкалиберные снаряды для пушки Mk3"],
"HVAPFSDS Cannon Rounds":["HVAPFSDS Снаряды Пушки"],
"HVAPFSDS Cannon Rounds Mk2":["HVAPFSDS Снаряды Пушки Мk2"],
"HVAPFSDS Cannon Rounds Mk3":["HVAPFSDS Снаряды Пушки Мk3"],
"Cannon Autoloader":["Автозарядка Пушки"],
"Cannon Autoloader Mk2":["Автозарядка Пушки Mk2"],
"Cannon Autoloader Mk3":["Автозарядка Пушки Mk2"],
"Cannon Rapid Loader":["Быстрая зарядка пушки"],
"Cannon Rapid Loader Mk2":["Быстрая зарядка пушки Мk2"],
"Cannon Rapid Loader Mk3":["Быстрая зарядка пушки Мk3"],
"Improved Laser Focusing":["Улучшенная фокусировка лазера"],
"Improved Laser Focusing Mk2":["Улучшенная фокусировка лазера Мk2"],
"Improved Laser Focusing Mk3":["Улучшенная фокусировка лазера Мk3"],
"Hi-Energy Laser Emitter":["Излучатель"],
"Hi-Energy Laser Emitter Mk2":["Излучатель Мk2"],
"Hi-Energy Laser Emitter Mk3":["Излучатель Мk3"],
"Thermopole Energizer":["Активизатор"],
"Thermopole Energizer Mk2":["Активизатор Мk2"],
"Thermopole Energizer Mk3":["Активизатор Мk3"],
"High Temperature Flamer Gel":["Высокотемпературный огнемётный гель"],
"High Temperature Flamer Gel Mk2":["Высокотемпературный огнемётный гель Mk2"],
"High Temperature Flamer Gel Mk3":["Высокотемпературный огнемётный гель Mk3"],
"Superhot Flamer Gel":["Сверхгорячий огнемётный гель"],
"Superhot Flamer Gel Mk2":["Сверхгорячий огнемётный гель Mk2"],
"Superhot Flamer Gel Mk3":["Сверхгорячий огнемётный гель Mk3"],
"Flamer Autoloader":["Автозарядка огнемета"],
"Flamer Autoloader Mk2":["Автозарядка огнемета Мk2"],
"Flamer Autoloader Mk3":["Автозарядка огнемета Мk3"],
"Heavy Flamer - Inferno":["Тяжёлый огнемёт - Инферно"],
"Heavy Howitzer - Ground Shaker":["Тяжелая гаубица - Сотрясатель"],
"Rotary Howitzer - Hellstorm":["Роторная гаубица - Шторм Ада"],
"Target Acquisition Artillery Shells":["Снаряды гаубицы"],
"Target Acquisition Artillery Shells Mk2":["Снаряды гаубицы Мk2"],
"Target Prediction Artillery Shells":["Снаряды целевого прогноза гаубицы"],
"HE Howitzer Shells":["Разрывные Снаряды гаубицы"],
"HE Howitzer Shells Mk2":["Разрывные Снаряды гаубицы Мk2"],
"HE Howitzer Shells Mk3":["Разрывные Снаряды гаубицы Мk3"],
"HEAP Howitzer Shells":["Бронебойные Снаряды гаубицы"],
"HEAP Howitzer Shells Mk2":["Бронебойные Снаряды гаубицы Мk2"],
"HEAP Howitzer Shells Mk3":["Бронебойные Снаряды гаубицы Мk3"],
"Howitzer Autoloader":["Автозарядка Гаубицы"],
"Howitzer Autoloader Mk2":["Автозарядка Гаубицы Мk2"],
"Howitzer Autoloader Mk3":["Автозарядка Гаубицы Мk3"],
"Laser - Flashlight":["Лазер - Вспышка"],
"Hardened MG Bullets":["Усиленные пули "],
"APDSB MG Bullets":["APDSB пули"],
"APDSB MG Bullets Mk2":["APDSB пули Мk2"],
"APDSB MG Bullets Mk3":["APDSB пули Мk3"],
"Tungsten-Tipped MG Bullets":["Вольфрамовые пули"],
"Tungsten-Tipped MG Bullets Mk2":["Вольфрамовые пули Мk2"],
"Tungsten-Tipped MG Bullets Mk3":["Вольфрамовые пули Мk3"],
"Depleted Uranium MG Bullets":["Пули из обедненного урана"],
"Depleted Uranium MG Bullets Mk2":["Пули из обедненного урана Мk2"],
"Chaingun Upgrade":["Улучшение Пулемета"],
"Hyper Fire Chaingun Upgrade":["Улучшение гиперскоростного пулемета"],
"Target Prediction Missiles":["Ракеты целевого прогноза"],
"Search & Destroy Missiles":["Ракеты Найти и уничтожить"],
"Advanced Missile Warhead":["Продвинутая боеголовка"],
"Advanced Missile Warhead Mk2":["Продвинутая боеголовка Mk2"],
"Advanced Missile Warhead Mk3":["Продвинутая боеголовка Mk3"],
"Advanced Missile Allocation System":["Система обнаружения ракет"],
"Advanced Missile Allocation System Mk2":["Система обнаружения ракет Мk2"],
"Advanced Missile Allocation System Mk3":["Система обнаружения ракет Мk3"],
"HEAP Missile Warhead":["Взрывчатая бронебойная боеголовка"],
"HEAP Missile Warhead Mk2":["Взрывчатая бронебойная боеголовка Mk2"],
"HEAP Missile Warhead Mk3":["Взрывчатая бронебойная боеголовка Mk3"],
"Improved Missile Loading System":["Улучшенная система загрузки ракет"],
"Mortar Targeting Computer":["Компьютерное наведение снарядов мортиры"],
"Thermal Imaging Mortar Shells":["Тепловое наведение снарядов мортиры"],
"Target Acquisition Mortar Shells":["Автозахват цели минометами"],
"HE Mortar Shells":["Разрывные снаряды миномета"],
"HE Mortar Shells Mk2":["Разрывные снаряды миномета Мk2"],
"HE Mortar Shells Mk3":["Разрывные снаряды миномета Мk3"],
"HEAP Mortar Shells":["Бронебойные снаряды миномета"],
"HEAP Mortar Shells Mk2":["Бронебойные снаряды миномета Мk2"],
"HEAP Mortar Shells Mk3":["Бронебойные снаряды миномета Мk3"],
"Mortar Autoloader":["Автозарядка миномета"],
"Mortar Autoloader Mk2":["Автозарядка миномета Мk2"],
"Mortar Autoloader Mk3":["Автозарядка миномета Мk3"],
"Mortar Fast Loader":["Быстрая зарядка миномета"],
"Heavy Mortar - Bombard":["Тяжелый миномет- Бомбард"],
"Rotary Mortar - Pepperpot":["Роторный миномет - Пепперпот"],
"Hardened Rail Dart":["Усиленные шипы"],
"Hardened Rail Dart Mk2":["Усиленные шипы Мk2"],
"Hardened Rail Dart Mk3":["Усиленные шипы Мk3"],
"Rail Gun ROF":["Скоростная рельсопушка"],
"Rail Gun ROF Mk2":["Скоростная рельсопушка Мk2"],
"Rail Gun ROF Mk3":["Скоростная рельсопушка Мk3"],
"Rapid Fire Mini-Rockets":["Быстрая зарядка миниракет"],
"Rapid Fire Mini-Rockets Mk2":["Быстрая зарядка миниракет Мk2"],
"Rapid Fire Mini-Rockets Mk3":["Быстрая зарядка миниракет Мk3"],
"Improved Rocket Wire Guidance":["Улучшенное наведение ракет"],
"Rocket Laser Designator":["Ракетный лазерный целеуказатель"],
"Thermal Imaging Rockets":["Ракеты с теплонаведением"],
"HEAT Rocket Warhead":["Противотанковая ракетная боеголовка"],
"HEAT Rocket Warhead Mk2":["Противотанковая ракетная боеголовка Мk2"],
"HEAT Rocket Warhead Mk3":["Противотанковая ракетная боеголовка Mk3"],
"HESH Rocket Warhead":["Усиленная ракетная боеголовка"],
"HESH Rocket Warhead Mk2":["Усиленная ракетная боеголовка Мk2"],
"HESH Rocket Warhead Mk3":["Усиленная ракетная боеголовка Мk3"],
"Rocket Autoloader":["Автозарядка ракет"],
"Rocket Autoloader Mk2":["Автозарядка ракет Мk2"],
"Rocket Autoloader Mk3":["Автозарядка ракет Мk3"],
"Lancer AT Rocket":["Противотанковая ракета Лансер"],
"Bunker Buster Rocket":["Ракета Антибункер"],
"Tank Killer Rocket":["Ракета Танк-Киллер"],
"Machinegun Artifact":["Артефакт Пулемет"],
"New Paradigm Command Center":["Командный центр Новой Парадигмы"],
"Collective Command Center":["Командный центр Альянса"],
"Scavenger Factory":["Фабрика Мусорщиков"],
"Scavenger Gun Tower":["Пулемётная башня Мусорщиков"],
"Scavenger Horizontal Wall":["Продольная стена Мусорщиков"],
"Scavenger Power Generator":["Генератор энергии Мусорщиков"],
"Scavenger Rocket Pit":["Ракетный окоп Мусорщиков"],
"Scavenger AT-Rocket Pit":["Окоп противотанковых ракет Мусорщиков"],
"Scavenger Bunker":["Бункер Мусорщиков"],
"Scavenger CornerWall":["Угловая стена Мусорщиков"],
"Scavenger Flame Tower":["Огнемётная башня Мусорщиков"],
"Scavenger Flame Tower End":["Башня с огнеметом Мусорщиков"],
"Look-Out Tower":["Наблюдательная вышка"],
"Cannon Tower":["Башня с пушкой"],
"Artifact":["Артефакт"],
"Oil Resource":["Нефтяной ресурс"],
"Bridge":["Мост"],
"Ruined Factory":["Разрушенная фабрика"],
"Warehouse":["Склад"],
"Hut":["Лачуга"],
"Oil Drum":["Бочка с нефтью"],
"Wreck":["Обломки"],
"Wrecked Tank":["Разрушенный танк"],
"Wrecked Bridge":["Разрушенный мост"],
"Wrecked Van":["Разрушенный фургон"],
"Wrecked Vehicle":["Разрушенная машина"],
"Wrecked Tanker":["Разрушенный танкер"],
"Cyborg Laboratory":["Лаборатория киборгов"],
"Advanced Warfare Laboratory":["Передовая военная лаборатория"],
"Engineering Laboratory":["Инженерная лаборатория"],
"Robotics Laboratory":["Лаборатория робототехники"],
"Laser Optics Laboratory":["Лаборатория лазерной оптики"],
"Electronics Laboratory":["Лаборатория электроники"],
"Chemical Laboratory":["Химическая лаборатория"],
"Advanced Warfare":["Продвинутые методы ведения войны"],
"Railgun Emplacement":["Установка Рельсовой Пушки"],
"Archangel Missile Emplacement":["Установка ракет Архангел"],
"Repair Turret Cobra Tracks":["Ремонтная Кобра Гусеницы"],
"Scourge":["Бич"],
"Bunker Blaster":["Антибункер"],
"Flashlight Gunner":["Вспышка-стрелок"],
"Needle Gunner":["Иглометчик"],
"Downed Transport":["Приземлившийся транспорт"],
"Tank Killer Python Tracks":["Танк-Киллер Питон Гусеницы"],
"Assault Gun Python Tracks":["Штурмовое орудие Питон Гусеницы"],
"Flashlight":["Вспышка"],
"VTOL Flashlight":["ВВС Вспышка"],
"Rotary MG Bunker":["Бункер с роторным пулеметом"],
"Missile Silo":["Ракетная шахта"],
"Cyborg Transport":["КиберТранспорт"],
"Light Cannon Viper Half-tracks":["Легкая пушка Гадюка Полугусеницы"],
"Repair Turret Viper Half-track":["Ремонтная Гадюка Полугусеницы"],
"Mini-Rocket Array Viper Wheels":["Блок миниракет Гадюка Колёса"],
"Bunker Buster Rockets Viper Wheels":["Антибункер Гадюка Колеса"],
"Sensor Turret Cobra Half-tracks":["Башня с датчиком на полугусеничном ходу"],
"Mini-Rocket Array Cobra Half-tracks":["Батарея миниракет Кобра на полугусеницы"],
"Jammer Tower":["Глушительная башня"],
"Jammer Turret":["Глушительная туррель"],
"Electronic Countermeasures":["Электронные контрмеры"],
"Radar Detector":["Обнаружитель датчиков"],
"Radar Detector Tower":["Башня с Детектором датчиков"],
"Nexus Link":["Нейросвязь НЕКСУС"],
"Nexus Link Turret":["Турель нейросвязи НЕКСУС"],
"Hardcrete Gate":["Хардкритовая стена."],
"Inferno Bunker":["Инферно бункер"],
"Tornado AA Site":["Зенитка Торнадо"],
"AA Flak Cannon Emplacement":["Установка орудия зенитной пушки."],
"Pulse Laser Hardpoint":["Укрепленная точка с импульсным лазером"],
"Pulse Laser Tower":["Башня с Импульсным лазером"],
"Seraph Missile Array":["Ракетный блок Серафим"],
"Mini-Rocket Array":["Блок миниракет"],
"AA Flak Cannon":["Зенитная пушка."],
"VTOL Flak Cannon":["Авиационная пушка"],
"Laser Satellite Command Post":["Центр Управления Лазернми спутниками"],
"VTOL Cluster Bomb Bay":["ВВС Кластерные бомбы"],
"Collective Corner Wall":["Угловая стена Альянса"],
"Nexus Wall":["Стена НЕКСУС"],
"Nexus Corner Wall":["Угловая стена НЕКСУС"],
"Super Transport":["Супер-Транспорт."],
"Super Transport Body":["Корпус Супер-транспорта"],
"Plasteel":["Пласталь"],
"Plasteel Mk2":["Пласталь МК2"],
"Plasteel Mk3":["Пласталь МК3"],
"Hyper Velocity Cannon Emplacement":["Установка ГС пушки"],
"Seraph Missile Battery":["Батарея ракет Сериафим"],
"Flamer Tower":["Башня с огнеметом"],
"Hyper Velocity Cannon Hardpoint":["Укрепточка с ГС пушкой"],
"Automated Manufacturing":["Автоматизированное производство"],
"Robotic Manufacturing":["Роботизированное производство"],
"Advanced Manufacturing":["Продвинутое производство"],
"Self-Replicating Manufacturing":["Саморепликация производства"],
"Advanced Manufacturing Mk3":["Продвинутое производство Мk3"],
"Robotic Repair Facility":["Роботизированная мастерская"],
"Advanced Repair Facility":["Продвинутая ремонтная мастерская"],
"Robotic Repair Facility Mk3":["Роботизированная мастерская Мk3"],
"Advanced Repair Facility Mk2":["Продвинутая ремонтная мастерская Мk2"],
"Advanced Repair Facility Mk3":["Продвинутая ремонтная мастерская Мk3"],
"Auto-Repair":["Автопочинка"],
"Heavy Repair Turret":["Тяжелая ремонтная туррель"],
"Nexus Intruder Program":["Программы захвата НЕКСУС"],
"Nexus Resistance Circuits":["Программы сопротивления НЕКСУС"],
"Nexus Resistance Circuits Mk2":["Программы сопротивления НЕКСУС Мk2"],
"Nexus Resistance Circuits Mk3":["Программы сопротивления НЕКСУС Мk3"],
"Cluster Bomb Bay":["Отсек для кластерных бомб"],
"HE Bomb Shells":["Разрывные снаряды для бомб"],
"Improved Bomb Warhead":["Улучшенная бомбовая боеголовка"],
"Advanced Bomb Warhead":["Продвинутая бомбовая боеголовка"],
"Howitzer Fast Loader":["Быстрая Зарядка Гаубицы"],
"Rapid Fire Chaingun":["Скоростной зарядчик пулемета"],
"Rail Target Prediction Computer":["Кмпьютерное наведение рельсовых орудий"],
"Stabilized Rockets":["Стабилизированные ракеты"],
"HE Rockets":["Разрывные ракеты"],
"HE Rockets Mk2":["Разрывные ракеты Мk2"],
"HE Rockets Mk3":["Разрывные ракеты Мk3"],
"Assault Gun Tower":["Бышня со Штурмовым орудием"],
"Repair Cobra Tracks":["Ремонтная Кобра Гусеницы"],
"Hyper Velocity Cannon Python Tracks":["ГС пушка питон гусеницы"],
"AA Flak Cannon Python Half-tracks":["Питон на гусеницах с тяжелой пушкой"],
"Bunker Buster Cobra Hover":["Антибункер Кобра Ховер"],
"Sensor Upgrade Mk2":["Улучшение датчика Мk2"],
"Sensor Upgrade Mk3":["Улучшение датчика Мk3"],
"Vapor Turbine Generator Mk2":["Паротурбинный генератор Мk2"],
"Gas Turbine Generator Mk2":["Газотурбинный генератор МК2"],
"Gas Turbine Generator Mk3":["Газотурбинный генератор Мk3"],
"Vapor Turbine Generator Mk3":["Паротурбинный генератор Мk3"],
"Thermite Flamer":["Термитный огнёмет"],
"Grenadier":["Миномётчик"],
"Combat Engineer":["Военный инженер"],
"Cyborg Mechanic":["Киборг-механик"],
"Incendiary Howitzer":["Адская гаубица"],
"Incendiary Howitzer Emplacement":["Установка Адской гаубицы"],
"Plasmite Flamer":["Плазменный огнемет"],
"Plasmite Flamer Bunker":["Бункер с плазменным огнемётом"],
"Incendiary Mortar":["Адский миномет"],
"Incendiary Mortar Pit":["Адский минометный окоп"],
"Cyborg Superdense Thermal Armor":["Суперпрочная термоброня киборга"],
"Cyborg Superdense Thermal Armor Mk2":["Суперпрочная термоброня киборга Мk2"],
"Cyborg Superdense Thermal Armor Mk3":["Суперпрочная термоброня киборга Мk3"],
"Vehicle Superdense Thermal Armor":["Суперпрочная термоброня"],
"Vehicle Superdense Thermal Armor Mk2":["Суперпрочная термоброня Мk2"],
"Vehicle Superdense Thermal Armor Mk3":["Суперпрочная термоброня Мk3"],
"Super Heavy-Gunner":["Супертяжелый стрелок"],
"Super Auto-Cannon Cyborg":["Супер автоматчик"],
"Super HPV Cyborg":["Супер ГСП стрелок"],
"Super Tank-Killer Cyborg":["Супер Танк-Киллер"],
"Heavy Laser":["Тяжёлый лазер"],
"VTOL Heavy Laser":["Тяжёлый лазер ВВС"],
"Heavy Laser Emplacement":["Установка тяжелого лазера"],
"Twin Assault Cannon":["Спаренная штурмовая пушка"],
"Twin Assault Cannon Bunker":["Бункер с двойной штурмовой пушкой"],
"Satellite Uplink Center":["Центр связи со спутником"],
"Wide Spectrum Sensor":["Датчик расширенного спектра"],
"Wide Spectrum Sensor Tower":["Башня с датчиком расширенного спектра"],
"Plasma Cannon":["Плазменная пушка"],
"Plasma Cannon Emplacement":["Установка плазменной пушки"],
"Sunburst AA Rocket Array":["Установка ракет - солнечные лучи"],
"Sunburst AA":["Противовоздушная ракета солнечный луч"],
"VTOL Sunburst AA":["Авиационная установка солнечный луч"],
"Sunburst AA Site":["Площадка солнечных лучей"],
"Super Pulse Laser Cyborg":["Супер киборг с лазером"],
"Super Rail-Gunner":["Супер иглометчик"],
"Super Scourge Cyborg":["Супер Бич ракетометчик"],
"Nexus Link Tower":["Башня связи НЕКСУС"],
"EMP Cannon":["ЭМИ-пушка"],
"EMP Cannon Tower":["Башня ЭМИ пушки"],
"Mass Driver Fortress":["Крепость тяжелого рельсового орудия"],
"Mass Driver":["Тяжелое рельсовое орудие"],
"Cannon Fortress":["Крепость с пушкой"],
"Heavy Rocket Bastion":["Крепость тяжелых ракет"],
"Missile Fortress":["Крепость с тяжелой пусковой установкой"],
"Heavy Body - Wyvern":["Тяжелый корпус - Виверна"],
"Wyvern":["Виверна"],
"Multi Turret Body - Dragon":["Многоствольный корпус - Дракон"],
"Dragon":["Дракон"],
"Superhot Plasmite gel":["Супергорючая смесь Плазмы"],
"Superhot Plasmite gel Mk2":["Супергорючая смесь Плазмы Мk2"],
"Superhot Plasmite gel Mk3":["Супергорючая смесь Плазмы Мk3"],
"EMP Mortar":["ЭМИ миномет"],
"EMP Mortar Pit":["Установка с ЭМИ минометом"],
"Stormbringer AA Laser":["Лазерная зенитка Предвестник Бури"],
"Stormbringer Emplacement":["Установка Предвестника Бури"],
"Vindicator Hardpoint":["Укрепленная точка с пусковой Защитник"],
"Whirlwind Hardpoint":["Оборонительная точка Вихрь"],
"AA Flak Cannon Hardpoint":["Укрепленная точка с зенитной пушкой"],
"Avenger Hardpoint":["Оборонительная точка с Мститель"],
"Twin Assault Gun":["Спаренное штурмовое орудие"],
"Twin Assault Gun Hardpoint":["Укрепточка с двойным штурмовым орудием"],
"VTOL Plasmite Bomb Bay":["Плазменные Бомбы ВВС"],
"Plasmite Bomb":["Плазменные Бомбы"],
"VTOL EMP Missile Launcher":["ЭМИ ракета ВВС"],
"EMP Missile Launcher":["Пусковая ЭМИ ракет"],
"Command Turret II":["Командная II"],
"Command Turret III":["Командная III"],
"Command Turret IV":["Командная IV"],
"Heavy Repair Turret Cobra Hover":["Тяжелая ремонтная Кобра Ховер"],
"Heavy Machinegun Viper Wheels":["Тяжелый пулемёт Гадюка Колёса"],
"Scourge Mantis Hover":["Бич Богомол Ховер"],
"Tank Killer Mantis Hover":["Танк-Киллер Богомол Ховер"],
"Heavy Machinegun Cobra Tracks":["Тяжелый пулемёт Кобра Гусеницы"],
"Heavy Cannon Cobra Hover":["Тяжелая пушка Кобра Ховер"],
"Heavy Machinegun Cobra Wheels":["Тяжелый пулемёт Кобра Колёса"],
"Heavy Machinegun Cobra Hover":["Тяжелый пулемет Кобра Ховер"],
"Machinegun Viper Tracks":["Пулемёт Гадюка Гусеницы"],
"Twin Machinegun Viper Tracks":["Двойной пулемет Гадюка Гусеницы"],
"Medium Cannon Cobra Hover":["Средняя пушка Кобра Ховер"],
"Medium Cannon Scorpion Hover":["Средняя пушка Скорпион Ховер"],
"Medium Cannon Scorpion Tracks":["Средняя пушка Скорпион Гусеницы"],
"Medium Cannon Python Hover":["Средняя пушка Питон Ховер"],
"Heavy Cannon Python Hover":["Тяжелая пушка Питон Ховер"],
"Rail Gun Mantis Tracks":["Рельсовая пушка Богомол Гусеницы"],
"Pulse Laser Mantis Tracks":["Импульсный лазер Богомол Гусеницы"],
"Lancer Python Tracks":["Лансер Питон Гусеницы"],
"Lancer Mantis Tracks":["Лансер Богомол Гусеницы"],
"Tank Killer Vengeance Tracks":["Танк-Киллер Месть Гусеницы"],
"Heavy Cannon Tiger Tracks":["Тяжелая пушка Тигр Гусеницы"],
"Needle Gun Tiger Tracks":["Игломёт Тигр Гусеницы"],
"Needle Gun Retribution Tracks":["Игломёт Кара Гусеницы"],
"Needle Gun Vengeance Tracks":["Игломёт Месть Гусеницы"],
"Vengeance Tracks Rail Gun":["Месть Гусеницы Рельсовая пушка"],
"Vengeance Tracks Gauss Cannon":["Месть Гусеницы Пушка Гаусса"],
"Vengeance Tracks Gauss Scourge":["Месть Гусеницы Бич Гаусса"],
"VTOL Cluster Bomb Bay Bug VTOL":["ВВС Кластерные бомбы Жук"],
"VTOL Bunker Buster Bug VTOL":["ВВС Антибункер Жук "],
"VTOL Cluster Bomb Bay Scorpion VTOL":["ВВС Кластерные бомбы Скорпион"],
"VTOL Bunker Buster Scorpion VTOL":["ВВС Антибункер Скорпион"],
"VTOL Lancer Bug VTOL":["ВВП Лансер Жук"],
"VTOL Hyper Velocity Cannon Bug VTOL":["ВВС ГС пушка жук"],
"VTOL Lancer Scorpion VTOL":["ВВП Лансер Скорпион"],
"VTOL Hyper Velocity Cannon Scorpion VTOL":["ВВП ГС пушка скорпион"],
"VTOL Lancer Mantis VTOL":["ВВП Лансер Богомол"],
"VTOL Hyper Velocity Cannon Mantis VTOL":["ВВС ГС пушка Богомол"],
"Repair Turret Mantis Tracks":["Ремонтная Богомол Гусеницы"],
"Lancer Scorpion Tracks":["Лансер Скорпион Гусеницы"],
"Heavy Cannon Scorpion Tracks":["Тяжелая пушка Скорпион Гусеницы"],
"Lancer Scorpion VTOL":["Лансер Скорпион ВВП"],
"Bunker Buster Scorpion VTOL":["Антибункер Скорпион ВВП"],
"Command Turret Viper Tracks":["Командная Гадюка Гусеницы"],
"Command Turret Cobra Tracks":["Командная Кобра Гусеницы"],
"Command Turret Scorpion Tracks":["Командная Скорпион Гусеницы"],
"Command Turret Mantis Tracks":["Командная Богомол Гусеницы"],
"Lancer Cobra Tracks":["Лансер Кобра Гусеницы"],
"Heavy Cannon Mantis Tracks":["Тяжелая пушка Богомол Гусеницы"],
"Tank Killer Mantis Tracks":["Танк-Киллер Богомол Гусеницы"],
"Scourge Mantis Tracks":["Бич Богомол Гусеницы"],
"Heavy Machinegun Scorpion Tracks":["Тяжелый пулемёт Скорпион Гусеницы"],
"Repair Scorpion Tracks":["Ремонтная Скорпион Гусеницы"],
"Heavy Repair Scorpion Hover":["Тяжёлая ремонтная Скорпион Ховер"],
"Truck Cobra Hover":["Грузовик Кобра Ховер"],
"Truck Scorpion Hover":["Грузовик Скорпион Ховер"],
"Truck Mantis Hover":["Грузовик Богомол Ховер"],
"Bunker Buster Cobra Tracks":["Антибункер Кобра Гусеницы"],
"Bunker Buster Scorpion Tracks":["Антибункер Скорпион Гусеницы"],
"Bunker Buster Mantis Tracks":["Антибункер Богомол Гусеницы"],
"Lancer Viper Tracks":["Лансер Гадюка Гусеницы"],
"Mini-Rocket Cobra Half-Tracks":["Миниракеты Кобра Полугусеницы"],
"Mini-Rocket Cobra Tracks":["Миниракеты Кобра Гусеницы"],
"Mini-Rocket Array Cobra Tracks":["Блок миниракет Кобра Гусеницы"],
"Inferno Cobra Half-Tracks":["Инферно Кобра Полугусеницы"],
"Hyper Velocity Cannon Python Hover":["ГС пушка питон ховер"],
"Scourge Python Tracks":["Бич Питон Гусеницы"],
"Gauss Cannon Python Tracks":["Пушка Гаусса Питон Гусеницы"],
"Pulse Laser Python Tracks":["Импульсный лазер Питон Гусеницы"],
"Pulse Laser Tiger Tracks":["Импульсный лазер Тигр Гусеницы"],
"Heavy Laser Tiger Tracks":["Тяжёлый лазер Тигр Гусеницы"],
"Gauss Cannon Wyvern Tracks":["Пушка Гаусса Виверна Гусеницы"],
"Pulse Laser Wyvern Tracks":["Импульсный лазер Виверна Гусеницы"],
"Heavy Laser Wyvern Tracks":["Тяжёлый лазер Виверна Гусеницы"],
"Machinegun Viper Half-Tracks":["Пулемёт Гадюка Полугусеницы"],
"Flamer Viper Half-Tracks":["Огнемёт Гадюка Полугусеницы"],
"Inferno Cobra Hover":["Инферно Кобра Ховер"],
"Medium Cannon Cobra Half Track":["Средняя пушка Кобра Гусеницы"],
"Inferno Python Hover":["Инферно Питон Ховер"],
"Assault Gun Python Hover":["Штурмовое орудие Питон Ховер"],
"Assault Gun Python Half Track":["Штурмовое орудие Питон Полугусеницы"],
"Heavy Machinegun Scorpion Half Tracks":["Тяжелый пулемёт Скорпион Полугусеницы"],
"Assault Cannon Mantis Hover":["Осадная пушка Богомол Ховер"],
"Pulse Laser Leopard Hover":["Импульсный лазер Леопард Ховер"],
"Pulse Laser Panther Hover":["Импульсный лазер Пантера Ховер"],
"Rail Gun Tiger Hover":["Рельсовая пушка Тигр Ховер"],
"Pulse Laser Tiger Hover":["Импульсный лазер Тигр Ховер"],
"Plasma Cannon Wyvern Tracks":["Плазменная пушка Виверна Гусеницы"],
"Scourge Missile Wyvern Tracks":["Бич Виверна Гусеницы"],
"Flashlight Retribution Hover":["Вспышка Кара Ховер"],
"Mini-Rocket Viper Half Track":["Миниракеты Гадюка Полугусеницы"],
"Mini-Rocket Array Viper Half Track":["Блок миниракет Гадюка Гусеницы"],
"Phosphor Bomb Bay Mantis VTOL":["Фосфорные бомбы Богомол ВВС"],
"Heap Bomb Bay Mantis VTOL":["Бронебойные взрывчатые бомбы Богомол ВВС"],
"Heap Bomb Bay Retribution VTOL":["Бронебойные взрывчатые бомбы Кара ВВС"],
"Scourge Retaliation VTOL":["Бич Возмездие ВВС"],
"Plasmite Retribution VTOL":["Авиационный плазмит возмездия"],};