#!/bin/bash
mv "b1 L-A B Demolish Structure.tif" "B Demolish Structure.tif"
mv "b1 L-B B Scavenger Factory.tif" "B Scavenger Factory.tif"
mv "b1 L-C B Scavenger Gun Tower.tif" "B Scavenger Gun Tower.tif"
mv "b1 L-D B Scavenger Horizontal Wall.tif" "B Scavenger Horizontal Wall.tif"
mv "b1 L-E B Scavenger Power Generator.tif" "B Scavenger Power Generator.tif"
mv "b1 R-A B Scavenger Bunker.tif" "B Scavenger Bunker.tif"
mv "b1 R-B B Scavenger Flame Tower.tif" "B Scavenger Flame Tower.tif"
mv "b1 R-C B Scavenger End Tower.tif" "B Scavenger End Tower.tif"
mv "b1 R-D B BaBaMortarPit.tif" "B BaBaMortarPit.tif"
mv "b1 R-E B Scavenger Rocket Pit.tif" "B Scavenger Rocket Pit.tif"
mv "b2 L-A B Scavenger AT-Rocket Pit.tif" "B Scavenger AT-Rocket Pit.tif"
mv "b2 L-B B Collective Command Centre.tif" "B Collective Command Centre.tif"
mv "b2 L-C B New Paradigm Command Centre.tif" "B New Paradigm Command Centre.tif"
mv "b2 L-D B Factory Module.tif" "B Factory Module.tif"
mv "b2 L-E B Hardcrete Wall.tif" "B Hardcrete Wall.tif"
mv "b2 R-A B Cannon Tower.tif" "B Cannon Tower.tif"
mv "b2 R-B B CommandCentreNE.tif" "B CommandCentreNE.tif"
mv "b2 R-C B Cyborg Factory.tif" "B Cyborg Factory.tif"
mv "b2 R-D B Hardcrete Gate.tif" "B Hardcrete Gate.tif"
mv "b2 R-E B Laser Satellite Command Post.tif" "B Laser Satellite Command Post.tif"
mv "b3 L-A B Power Generator.tif" "B Power Generator.tif"
mv "b3 L-B B Repair Facility.tif" "B Repair Facility.tif"
mv "b3 L-C B Oil Derrick.tif" "B Oil Derrick.tif"
mv "b3 L-D B Tank Traps.tif" "B Tank Traps.tif"
mv "b3 L-E B VTOL Rearming Pad.tif" "B VTOL Rearming Pad.tif"
mv "b3 R-A B Power Module.tif" "B Power Module.tif"
mv "b3 R-B B Research Module.tif" "B Research Module.tif"
mv "b3 R-C B Satellite Uplink Centre.tif" "B Satellite Uplink Centre.tif"
mv "b3 R-D B VTOL Factory.tif" "B VTOL Factory.tif"
mv "b3 R-E B AA Flak Cannon Emplacement.tif" "B AA Flak Cannon Emplacement.tif"
mv "b4 L-A B Hurricane AA Site.tif" "B Hurricane AA Site.tif"
mv "b4 L-B B Sunburst AA Site.tif" "B Sunburst AA Site.tif"
mv "b4 L-C B CO-Tower-HVCan.tif" "B CO-Tower-HVCan.tif"
mv "b4 L-D B CO-Tower-LtATRkt.tif" "B CO-Tower-LtATRkt.tif"
mv "b4 L-E B CO-Tower-MK3.tif" "B CO-Tower-MK3.tif"
mv "b4 R-A B Whirlwind AA Site.tif" "B Whirlwind AA Site.tif"
mv "b4 R-B B CO-Tower-HvATRkt.tif" "B CO-Tower-HvATRkt.tif"
mv "b4 R-C B CO-Tower-HvFlame.tif" "B CO-Tower-HvFlame.tif"
mv "b4 R-D B CO-Tower-MdCan.tif" "B CO-Tower-MdCan.tif"
mv "b4 R-E B CO-Tower-RotMG.tif" "B CO-Tower-RotMG.tif"
mv "b5 L-A B CO-WallTower-HvCan.tif" "B CO-WallTower-HvCan.tif"
mv "b5 L-B B Collective Wall.tif" "B Collective Wall.tif"
mv "b5 L-C B Heavy Laser Emplacement.tif" "B Heavy Laser Emplacement.tif"
mv "b5 L-D B Howitzer Emplacement.tif" "B Howitzer Emplacement.tif"
mv "b5 L-E B Hyper Velocity Cannon Emplacement.tif" "B Hyper Velocity Cannon Emplacement.tif"
mv "b5 R-A B CO-WallTower-RotCan.tif" "B CO-WallTower-RotCan.tif"
mv "b5 R-B B CoolingTower.tif" "B CoolingTower.tif"
mv "b5 R-C B Incendiary Howitzer Emplacement.tif" "B Incendiary Howitzer Emplacement.tif"
mv "b5 R-D B Ground Shaker Emplacement.tif" "B Ground Shaker Emplacement.tif"
mv "b5 R-E B Archangel Missile Emplacement.tif" "B Archangel Missile Emplacement.tif"
mv "b6 L-A B Tank Killer Emplacement.tif" "B Tank Killer Emplacement.tif"
mv "b6 L-B B EMP Mortar Pit.tif" "B EMP Mortar Pit.tif"
mv "b6 L-C B Mortar Pit.tif" "B Mortar Pit.tif"
mv "b6 L-D B Mini-Rocket Battery.tif" "B Mini-Rocket Battery.tif"
mv "b6 L-E B Flashlight Emplacement.tif" "B Flashlight Emplacement.tif"
mv "b6 R-A B Seraph Missile Battery.tif" "B Seraph Missile Battery.tif"
mv "b6 R-B B Incendiary Mortar Pit.tif" "B Incendiary Mortar Pit.tif"
mv "b6 R-C B Bombard Pit.tif" "B Bombard Pit.tif"
mv "b6 R-D B Plasma Cannon Emplacement.tif" "B Plasma Cannon Emplacement.tif"
mv "b6 R-E B Pulse Laser Emplacement.tif" "B Pulse Laser Emplacement.tif"
mv "b7 L-A B Railgun Emplacement.tif" "B Railgun Emplacement.tif"
mv "b7 L-B B Ripple Rocket Battery.tif" "B Ripple Rocket Battery.tif"
mv "b7 L-C B Pepperpot Pit.tif" "B Pepperpot Pit.tif"
mv "b7 L-D B Pulse Laser Tower.tif" "B Pulse Laser Tower.tif"
mv "b7 L-E B Assault Gun Tower.tif" "B Assault Gun Tower.tif"
mv "b7 R-A B Gauss Cannon Emplacement.tif" "B Gauss Cannon Emplacement.tif"
mv "b7 R-B B Hellstorm Emplacement.tif" "B Hellstorm Emplacement.tif"
mv "b7 R-C B Scourge Missile Tower.tif" "B Scourge Missile Tower.tif"
mv "b7 R-D B Needle Gun Tower.tif" "B Needle Gun Tower.tif"
mv "b7 R-E B Machinegun Guard Tower.tif" "B Machinegun Guard Tower.tif"
mv "b8 L-A B Twin Machinegun Guard Tower.tif" "B Twin Machinegun Guard Tower.tif"
mv "b8 L-B B Flamer Guard Tower.tif" "B Flamer Guard Tower.tif"
mv "b8 L-C B Mini-Rocket Tower.tif" "B Mini-Rocket Tower.tif"
mv "b8 L-D B NuclearReactor.tif" "B NuclearReactor.tif"
mv "b8 L-E B Missile Silo.tif" "B Missile Silo.tif"
mv "b8 R-A B Heavy Machinegun Tower.tif" "B Heavy Machinegun Tower.tif"
mv "b8 R-B B Lancer Tower.tif" "B Lancer Tower.tif"
mv "b8 R-C B Nexus Wall.tif" "B Nexus Wall.tif"
mv "b8 R-D B Missile Silo 2.tif" "B Missile Silo 2.tif"
mv "b8 R-E B NX-Emp-MedArtMiss-Pit.tif" "B NX-Emp-MedArtMiss-Pit.tif"
mv "b9 L-A B NX-Emp-MultiArtMiss-Pit.tif" "B NX-Emp-MultiArtMiss-Pit.tif"
mv "b9 L-B B NX-Tower-ATMiss.tif" "B NX-Tower-ATMiss.tif"
mv "b9 L-C B NX-Tower-Rail1.tif" "B NX-Tower-Rail1.tif"
mv "b9 L-D B NX-WallTower-Rail2.tif" "B NX-WallTower-Rail2.tif"
mv "b9 L-E B Stormbringer Emplacement.tif" "B Stormbringer Emplacement.tif"
mv "b9 R-A B NX-Emp-Plasma-Pit.tif" "B NX-Emp-Plasma-Pit.tif"
mv "b9 R-B B NX-Tower-PulseLas.tif" "B NX-Tower-PulseLas.tif"
mv "b9 R-C B NX-WallTower-BeamLas.tif" "B NX-WallTower-BeamLas.tif"
mv "b9 R-D B NX-WallTower-Rail3.tif" "B NX-WallTower-Rail3.tif"
mv "b9 R-E B Avenger SAM Site.tif" "B Avenger SAM Site.tif"
mv "b10 L-A B Vindicator SAM Site.tif" "B Vindicator SAM Site.tif"
mv "b10 L-B B Rotary MG Bunker.tif" "B Rotary MG Bunker.tif"
mv "b10 L-C B Twin Machinegun Bunker.tif" "B Twin Machinegun Bunker.tif"
mv "b10 L-D B Light Cannon Bunker.tif" "B Light Cannon Bunker.tif"
mv "b10 L-E B Lancer Bunker.tif" "B Lancer Bunker.tif"
mv "b10 R-A B Twin Assault Cannon Bunker.tif" "B Twin Assault Cannon Bunker.tif"
mv "b10 R-B B Machinegun Bunker.tif" "B Machinegun Bunker.tif"
mv "b10 R-C B Heavy Machinegun Bunker.tif" "B Heavy Machinegun Bunker.tif"
mv "b10 R-D B Flamer Bunker.tif" "B Flamer Bunker.tif"
mv "b10 R-E B Plasmite Flamer Bunker.tif" "B Plasmite Flamer Bunker.tif"
mv "b11 L-A B CB Tower.tif" "B CB Tower.tif"
mv "b11 L-B B Sys-NX-CBTower.tif" "B Sys-NX-CBTower.tif"
mv "b11 L-C B Sys-NX-VTOL-CB-Tow.tif" "B Sys-NX-VTOL-CB-Tow.tif"
mv "b11 L-D B Sensor Tower.tif" "B Sensor Tower.tif"
mv "b11 L-E B Wide Spectrum Sensor Tower.tif" "B Wide Spectrum Sensor Tower.tif"
mv "b11 R-A B Sys-NEXUSLinkTOW.tif" "B Sys-NEXUSLinkTOW.tif"
mv "b11 R-B B Sys-NX-SensorTower.tif" "B Sys-NX-SensorTower.tif"
mv "b11 R-C B Sys-NX-VTOL-RadTower.tif" "B Sys-NX-VTOL-RadTower.tif"
mv "b11 R-D B Hardened Sensor Tower.tif" "B Hardened Sensor Tower.tif"
mv "b11 R-E B Nexus Link Tower.tif" "B Nexus Link Tower.tif"
mv "b12 L-A B VTOL CB Tower.tif" "B VTOL CB Tower.tif"
mv "b12 L-B B Inferno Bunker.tif" "B Inferno Bunker.tif"
mv "b12 L-C B Assault Cannon Guard Tower.tif" "B Assault Cannon Guard Tower.tif"
mv "b12 L-D B Assault Cannon Hardpoint.tif" "B Assault Cannon Hardpoint.tif"
mv "b12 L-E B AA Flak Cannon Hardpoint.tif" "B AA Flak Cannon Hardpoint.tif"
mv "b12 R-A B VTOL Strike Tower.tif" "B VTOL Strike Tower.tif"
mv "b12 R-B B Assault Gun Emplacement.tif" "B Assault Gun Emplacement.tif"
mv "b12 R-C B UplinkCentre.tif" "B UplinkCentre.tif"
mv "b12 R-D B Scourge Missile Hardpoint.tif" "B Scourge Missile Hardpoint.tif"
mv "b12 R-E B EMP Cannon Tower.tif" "B EMP Cannon Tower.tif"
mv "b13 L-A B Hyper Velocity Cannon Hardpoint.tif" "B Hyper Velocity Cannon Hardpoint.tif"
mv "b13 L-B B Inferno Hardpoint.tif" "B Inferno Hardpoint.tif"
mv "b13 L-C B Whirlwind Hardpoint.tif" "B Whirlwind Hardpoint.tif"
mv "b13 L-D B Vindicator Hardpoint.tif" "B Vindicator Hardpoint.tif"
mv "b13 L-E B Heavy Machinegun Hardpoint.tif" "B Heavy Machinegun Hardpoint.tif"
mv "b13 R-A B Tank Killer Hardpoint.tif" "B Tank Killer Hardpoint.tif"
mv "b13 R-B B Pulse Laser Hardpoint.tif" "B Pulse Laser Hardpoint.tif"
mv "b13 R-C B Gauss Cannon Hardpoint.tif" "B Gauss Cannon Hardpoint.tif"
mv "b13 R-D B Twin Assault Gun Hardpoint.tif" "B Twin Assault Gun Hardpoint.tif"
mv "b13 R-E B Light Cannon Hardpoint.tif" "B Light Cannon Hardpoint.tif"
mv "b14 L-A B Medium Cannon Hardpoint.tif" "B Medium Cannon Hardpoint.tif"
mv "b14 L-B B Flamer Hardpoint.tif" "B Flamer Hardpoint.tif"
mv "b14 L-C B Downed Transport.tif" "B Downed Transport.tif"
mv "b14 L-D B Mass Driver Fortress.tif" "B Mass Driver Fortress.tif"
mv "b14 L-E B Heavy Rocket Bastion.tif" "B Heavy Rocket Bastion.tif"
mv "b14 R-A B Heavy Cannon Hardpoint.tif" "B Heavy Cannon Hardpoint.tif"
mv "b14 R-B B Lancer Hardpoint.tif" "B Lancer Hardpoint.tif"
mv "b14 R-C B Cannon Fortress.tif" "B Cannon Fortress.tif"
mv "b14 R-D B Missile Fortress.tif" "B Missile Fortress.tif"
mv "b14 R-E B Radar Detector Tower.tif" "B Radar Detector Tower.tif"
mv "b15 L-A B Jammer Tower.tif" "B Jammer Tower.tif"
echo -e "\e[92mConvert these files with GIMP Plugin - David's Batch Processor."
echo -e "\e[92mUse GIF format and 255 indexed colors for the output files."