#!/bin/bash
mv "c1 L-A Machinegunner.tif" "Machinegunner.tif"
mv "c1 L-B Heavy Gunner.tif" "Heavy Gunner.tif"
mv "c1 L-C Assault Gunner.tif" "Assault Gunner.tif"
mv "c1 L-D Flashlight Gunner.tif" "Flashlight Gunner.tif"
mv "c1 L-E Thermite Flamer.tif" "Thermite Flamer.tif"
mv "c1 R-A Cyborg Flamer.tif" "Cyborg Flamer.tif"
mv "c1 R-B Lancer.tif" "Lancer.tif"
mv "c1 R-C Scourge.tif" "Scourge.tif"
mv "c1 R-D Needle Gunner.tif" "Needle Gunner.tif"
mv "c1 R-E Grenadier.tif" "Grenadier.tif"
mv "c2 L-A Combat Engineering.tif" "Combat Engineering.tif"
mv "c2 L-B Super Heavy-Gunner.tif" "Super Heavy-Gunner.tif"
mv "c2 L-C Super Tank-Killer Cyborg.tif" "Super Tank-Killer Cyborg.tif"
mv "c2 L-D Super Pulse Laser Cyborg.tif" "Super Pulse Laser Cyborg.tif"
mv "c2 L-E Super Scourge Cyborg.tif" "Super Scourge Cyborg.tif"
mv "c2 R-A Cyborg Mechanic.tif" "Cyborg Mechanic.tif"
mv "c2 R-B Super Auto-Cannon Cyborg.tif" "Super Auto-Cannon Cyborg.tif"
mv "c2 R-C Super HPV Cyborg.tif" "Super HPV Cyborg.tif"
mv "c2 R-D Super Rail-Gunner.tif" "Super Rail-Gunner.tif"
echo -e "\e[92mConvert these files with GIMP Plugin - David's Batch Processor."
echo -e "\e[92mUse GIF format and 255 indexed colors for the output files."