#!/bin/bash
mv "w1 L-A T Machinegun.tif" "T Machinegun.tif"
mv "w1 L-B T Nexus Link Turret.tif" "T Nexus Link Turret.tif"
mv "w1 L-C T Mini-Rocket Array.tif" "T Mini-Rocket Array.tif"
mv "w1 L-D T Lancer.tif" "T Lancer.tif"
mv "w1 R-A T Alex Super Weapon.tif" "T Alex Super Weapon.tif"
mv "w1 R-B T Mini-Rocket Pod.tif" "T Mini-Rocket Pod.tif"
mv "w1 R-C T Sunburst AA.tif" "T Sunburst AA.tif"
mv "w1 R-D T Ripple Rockets.tif" "T Ripple Rockets.tif"
mv "w2 L-A T Tank Killer.tif" "T Tank Killer.tif"
mv "w2 L-B T Gauss Cannon.tif" "T Gauss Cannon.tif"
mv "w2 L-C T Needle Gun.tif" "T Needle Gun.tif"
mv "w2 L-D T Hurricane AA Turret.tif" "T Hurricane AA Turret.tif"
mv "w2 R-A T Bunker Buster.tif" "T Bunker Buster.tif"
mv "w2 R-B T Rail Gun.tif" "T Rail Gun.tif"
mv "w2 R-C T Whirlwind AA Turret.tif" "T Whirlwind AA Turret.tif"
mv "w2 R-D T Plasmite Flamer.tif" "T Plasmite Flamer.tif"
mv "w3 L-A T EMP Mortar.tif" "T EMP Mortar.tif"
mv "w3 L-B T Bombard.tif" "T Bombard.tif"
mv "w3 L-C T Incendiary Mortar.tif" "T Incendiary Mortar.tif"
mv "w3 L-D T Avenger SAM.tif" "T Avenger SAM.tif"
mv "w3 R-A T Pepperpot.tif" "T Pepperpot.tif"
mv "w3 R-B T Mortar.tif" "T Mortar.tif"
mv "w3 R-C T Seraph Missile Array.tif" "T Seraph Missile Array.tif"
mv "w3 R-D T Vindicator SAM.tif" "T Vindicator SAM.tif"
mv "w4 L-A T Archangel Missile.tif" "T Archangel Missile.tif"
mv "w4 L-B T Twin Assault Gun.tif" "T Twin Assault Gun.tif"
mv "w4 L-C T Heavy Machinegun.tif" "T Heavy Machinegun.tif"
mv "w4 R-A T Scourge Missile.tif" "T Scourge Missile.tif"
mv "w4 R-B T Assault Gun.tif" "T Assault Gun.tif"
mv "w4 R-C T Twin Machinegun.tif" "T Twin Machinegun.tif"
mv "w4 R-D T Plasma Cannon.tif" "T Plasma Cannon.tif"
mv "w5 L-A T Flashlight.tif" "T Flashlight.tif"
mv "w5 L-B T Ground Shaker.tif" "T Ground Shaker.tif"
mv "w5 L-C T Hellstorm.tif" "T Hellstorm.tif"
mv "w5 L-D T Heavy Laser.tif" "T Heavy Laser.tif"
mv "w5 R-A T Pulse Laser.tif" "T Pulse Laser.tif"
mv "w5 R-B T Howitzer.tif" "T Howitzer.tif"
mv "w5 R-C T Incendiary Howitzer.tif" "T Incendiary Howitzer.tif"
mv "w5 R-D T Inferno.tif" "T Inferno.tif"
mv "w6 L-A T Flamer.tif" "T Flamer.tif"
mv "w6 L-B T Twin Assault Cannon.tif" "T Twin Assault Cannon.tif"
mv "w6 L-C T AA Flak Cannon.tif" "T AA Flak Cannon.tif"
mv "w6 L-D T Heavy Cannon.tif" "T Heavy Cannon.tif"
mv "w6 R-A T EMP Cannon.tif" "T EMP Cannon.tif"
mv "w6 R-B T Assault Cannon.tif" "T Assault Cannon.tif"
mv "w6 R-C T Hyper Velocity Cannon.tif" "T Hyper Velocity Cannon.tif"
mv "w6 R-D T Medium Cannon.tif" "T Medium Cannon.tif"
mv "w7 L-A T Light Cannon.tif" "T Light Cannon.tif"
mv "w7 R-A T Stormbringer AA Laser.tif" "T Stormbringer AA Laser.tif"
echo -e "\e[92mConvert these files with GIMP Plugin - David's Batch Processor."
echo -e "\e[92mUse GIF format and 255 indexed colors for the output files."