#!/bin/bash
mv "b1 L-A Tiger.tif" "Tiger.tif"
mv "b1 L-B Retribution.tif" "Retribution.tif"
mv "b1 L-C Cobra.tif" "Cobra.tif"
mv "b1 L-D Retaliation.tif" "Retaliation.tif"
mv "b1 R-A Scorpion.tif" "Scorpion.tif"
mv "b1 R-B Panther.tif" "Panther.tif"
mv "b1 R-C Bug.tif" "Bug.tif"
mv "b1 R-D Leopard.tif" "Leopard.tif"
mv "b2 L-A Viper.tif" "Viper.tif"
mv "b2 L-B Wyvern.tif" "Wyvern.tif"
mv "b2 L-C Python.tif" "Python.tif"
mv "b2 R-A Dragon.tif" "Dragon.tif"
mv "b2 R-B Mantis.tif" "Mantis.tif"
mv "b2 R-C Vengeance.tif" "Vengeance.tif"
mv "b3 L-A Cyborg Transport.tiff" "Cyborg Transport.tiff"
mv "b3 R-A Super Transport.tiff" "Super Transport.tiff"
echo -e "\e[92mConvert these files with GIMP Plugin - David's Batch Processor."
echo -e "\e[92mUse GIF format and 255 indexed colors for the output files."