#!/bin/bash
mv "r1 L-A Vehicle Superdense Thermal Armour.tif" "Vehicle Superdense Thermal Armour.tif"
mv "r1 L-B Vehicle Superdense Thermal Armour Mk3.tif" "Vehicle Superdense Thermal Armour Mk3.tif"
mv "r1 L-C Hover Propulsion.tif" "Hover Propulsion.tif"
mv "r1 L-D Light Body – Retaliation.tif" "Light Body – Retaliation.tif"
mv "r1 L-E Medium Body - Cobra.tif" "Medium Body - Cobra.tif"
mv "r1 R-A Vehicle Superdense Thermal Armour Mk2.tif" "Vehicle Superdense Thermal Armour Mk2.tif"
mv "r1 R-B Tracked Propulsion.tif" "Tracked Propulsion.tif"
mv "r1 R-C Light Body – Leopard.tif" "Light Body – Leopard.tif"
mv "r1 R-D Light Body – Bug.tif" "Light Body – Bug.tif"
mv "r1 R-E Medium Body - Panther.tif" "Medium Body - Panther.tif"
mv "r2 L-A Medium Body - Retribution.tif" "Medium Body - Retribution.tif"
mv "r2 L-B Heavy Body - Tiger.tif" "Heavy Body - Tiger.tif"
mv "r2 L-C Heavy Body - Python.tif" "Heavy Body - Python.tif"
mv "r2 L-D Fuel Injection Engine.tif" "Fuel Injection Engine.tif"
mv "r2 L-E Fuel Injection Engine Mk3.tif" "Fuel Injection Engine Mk3.tif"
mv "r2 R-A Medium Body - Scorpion.tif" "Medium Body - Scorpion.tif"
mv "r2 R-B Heavy Body - Vengeance.tif" "Heavy Body - Vengeance.tif"
mv "r2 R-C Heavy Body - Mantis.tif" "Heavy Body - Mantis.tif"
mv "r2 R-D Fuel Injection Engine Mk2.tif" "Fuel Injection Engine Mk2.tif"
mv "r2 R-E Composite Alloys.tif" "Composite Alloys.tif"
mv "r3 L-A Composite Alloys Mk2.tif" "Composite Alloys Mk2.tif"
mv "r3 L-B Half-tracked Propulsion.tif" "Half-tracked Propulsion.tif"
mv "r3 L-C Dense Composite Alloys.tif" "Dense Composite Alloys.tif"
mv "r3 L-D Dense Composite Alloys Mk3.tif" "Dense Composite Alloys Mk3.tif"
mv "r3 L-E Superdense Composite Alloys Mk2.tif" "Superdense Composite Alloys Mk2.tif"
mv "r3 R-A Composite Alloys Mk3.tif" "Composite Alloys Mk3.tif"
mv "r3 R-B VTOL Propulsion.tif" "VTOL Propulsion.tif"
mv "r3 R-C Dense Composite Alloys Mk2.tif" "Dense Composite Alloys Mk2.tif"
mv "r3 R-D Superdense Composite Alloys.tif" "Superdense Composite Alloys.tif"
mv "r3 R-E Superdense Composite Alloys Mk3.tif" "Superdense Composite Alloys Mk3.tif"
mv "r4 L-A Incendiary Howitzer.tif" "Incendiary Howitzer.tif"
mv "r4 L-B Incendiary Mortar.tif" "Incendiary Mortar.tif"
mv "r4 L-C Lancer AT Rocket.tif" "Lancer AT Rocket.tif"
mv "r4 L-D Light Cannon.tif" "Light Cannon.tif"
mv "r4 L-E Twin Machinegun.tif" "Twin Machinegun.tif"
mv "r4 R-A Plasmite Flamer.tif" "Plasmite Flamer.tif"
mv "r4 R-B Mini-Rocket Pod.tif" "Mini-Rocket Pod.tif"
mv "r4 R-C Sunburst AA Rocket Array.tif" "Sunburst AA Rocket Array.tif"
mv "r4 R-D Machinegun.tif" "Machinegun.tif"
mv "r4 R-E Heavy Machinegun.tif" "Heavy Machinegun.tif"
mv "r5 L-A Medium Cannon.tif" "Medium Cannon.tif"
mv "r5 L-B Mortar.tif" "Mortar.tif"
mv "r5 L-C Heavy Mortar - Bombard.tif" "Heavy Mortar - Bombard.tif"
mv "r5 L-D Heavy Cannon.tif" "Heavy Cannon.tif"
mv "r5 L-E Howitzer.tif" "Howitzer.tif"
mv "r5 R-A Mini-Rocket Array.tif" "Mini-Rocket Array.tif"
mv "r5 R-B Flamer.tif" "Flamer.tif"
mv "r5 R-C Hyper Velocity Cannon.tif" "Hyper Velocity Cannon.tif"
mv "r5 R-D Ripple Rockets.tif" "Ripple Rockets.tif"
mv "r5 R-E Hardened MG Bullets.tif" "Hardened MG Bullets.tif"
mv "r6 L-A Chaingun Upgrade.tif" "Chaingun Upgrade.tif"
mv "r6 L-B Rapid Fire Chaingun.tif" "Rapid Fire Chaingun.tif"
mv "r6 L-C Hyper Fire Chaingun Upgrade.tif" "Hyper Fire Chaingun Upgrade.tif"
mv "r6 L-D High Temperature Flamer Gel Mk2.tif" "High Temperature Flamer Gel Mk2.tif"
mv "r6 L-E Flamer Autoloader.tif" "Flamer Autoloader.tif"
mv "r6 R-A APDSB MG Bullets.tif" "APDSB MG Bullets.tif"
mv "r6 R-B APDSB MG Bullets Mk2.tif" "APDSB MG Bullets Mk2.tif"
mv "r6 R-C High Temperature Flamer Gel.tif" "High Temperature Flamer Gel.tif"
mv "r6 R-D High Temperature Flamer Gel Mk3.tif" "High Temperature Flamer Gel Mk3.tif"
mv "r6 R-E Flamer Autoloader Mk2.tif" "Flamer Autoloader Mk2.tif"
mv "r7 L-A Flamer Autoloader Mk3.tif" "Flamer Autoloader Mk3.tif"
mv "r7 L-B HEAT Cannon Shells Mk2.tif" "HEAT Cannon Shells Mk2.tif"
mv "r7 L-C Cannon Autoloader.tif" "Cannon Autoloader.tif"
mv "r7 L-D HE Mortar Shells Mk2.tif" "HE Mortar Shells Mk2.tif"
mv "r7 L-E Mortar Autoloader.tif" "Mortar Autoloader.tif"
mv "r7 R-A HEAT Cannon Shells.tif" "HEAT Cannon Shells.tif"
mv "r7 R-B HEAT Cannon Shells Mk3.tif" "HEAT Cannon Shells Mk3.tif"
mv "r7 R-C HE Mortar Shells.tif" "HE Mortar Shells.tif"
mv "r7 R-D HE Mortar Shells Mk3.tif" "HE Mortar Shells Mk3.tif"
mv "r7 R-E Mortar Autoloader Mk2.tif" "Mortar Autoloader Mk2.tif"
mv "r8 L-A Mortar Autoloader Mk3.tif" "Mortar Autoloader Mk3.tif"
mv "r8 L-B Cannon Laser Rangefinder.tif" "Cannon Laser Rangefinder.tif"
mv "r8 L-C Assault Cannon.tif" "Assault Cannon.tif"
mv "r8 L-D Heavy Flamer - Inferno.tif" "Heavy Flamer - Inferno.tif"
mv "r8 L-E Assault Gun.tif" "Assault Gun.tif"
mv "r8 R-A Bunker Buster Rocket.tif" "Bunker Buster Rocket.tif"
mv "r8 R-B Heavy Howitzer – Ground Shaker.tif" "Heavy Howitzer – Ground Shaker.tif"
mv "r8 R-C AA Flak Cannon.tif" "AA Flak Cannon.tif"
mv "r8 R-D Rotary Howitzer - Hellstorm.tif" "Rotary Howitzer - Hellstorm.tif"
mv "r8 R-E Rotary Mortar - Pepperpot.tif" "Rotary Mortar - Pepperpot.tif"
mv "r9 L-A Hurricane AA Turret.tif" "Hurricane AA Turret.tif"
mv "r9 L-B Laser - Flashlight.tif" "Laser - Flashlight.tif"
mv "r9 L-C Scourge Missile.tif" "Scourge Missile.tif"
mv "r9 L-D Rail Gun.tif" "Rail Gun.tif"
mv "r9 L-E APFSDS Cannon Rounds.tif" "APFSDS Cannon Rounds.tif"
mv "r9 R-A Whirlwind AA Turret.tif" "Whirlwind AA Turret.tif"
mv "r9 R-B Pulse Laser.tif" "Pulse Laser.tif"
mv "r9 R-C Needle Gun.tif" "Needle Gun.tif"
mv "r9 R-D Gauss Cannon.tif" "Gauss Cannon.tif"
mv "r9 R-E APFSDS Cannon Rounds Mk2.tif" "APFSDS Cannon Rounds Mk2.tif"
mv "r10 L-A APFSDS Cannon Rounds Mk3.tif" "APFSDS Cannon Rounds Mk3.tif"
mv "r10 L-B HVAPFSDS Cannon Rounds Mk2.tif" "HVAPFSDS Cannon Rounds Mk2.tif"
mv "r10 L-C Cannon Autoloader Mk2.tif" "Cannon Autoloader Mk2.tif"
mv "r10 L-D Cannon Rapid Loader.tif" "Cannon Rapid Loader.tif"
mv "r10 L-E Cannon Rapid Loader Mk3.tif" "Cannon Rapid Loader Mk3.tif"
mv "r10 R-A HVAPFSDS Cannon Rounds.tif" "HVAPFSDS Cannon Rounds.tif"
mv "r10 R-B HVAPFSDS Cannon Rounds Mk3.tif" "HVAPFSDS Cannon Rounds Mk3.tif"
mv "r10 R-C Cannon Autoloader Mk3.tif" "Cannon Autoloader Mk3.tif"
mv "r10 R-D Cannon Rapid Loader Mk2.tif" "Cannon Rapid Loader Mk2.tif"
mv "r10 R-E Cannon Laser Designator.tif" "Cannon Laser Designator.tif"
mv "r11 L-A Tank Killer Rocket.tif" "Tank Killer Rocket.tif"
mv "r11 L-B Synaptic Link Data Analysis.tif" "Synaptic Link Data Analysis.tif"
mv "r11 L-C Synaptic Link Data Analysis Mk3.tif" "Synaptic Link Data Analysis Mk3.tif"
mv "r11 L-D Heavy Repair Turret.tif" "Heavy Repair Turret.tif"
mv "r11 L-E Sensor Turret.tif" "Sensor Turret.tif"
mv "r11 R-A Command Turret.tif" "Command Turret.tif"
mv "r11 R-B Synaptic Link Data Analysis Mk2.tif" "Synaptic Link Data Analysis Mk2.tif"
mv "r11 R-C Power Module.tif" "Power Module.tif"
mv "r11 R-D Sensor Tower.tif" "Sensor Tower.tif"
mv "r11 R-E Engineering.tif" "Engineering.tif"
mv "r12 L-A Mobile Repair Turret.tif" "Mobile Repair Turret.tif"
mv "r12 L-B Nexus Link Turret.tif" "Nexus Link Turret.tif"
mv "r12 L-C Hardened Sensor Tower.tif" "Hardened Sensor Tower.tif"
mv "r12 L-D Factory Module.tif" "Factory Module.tif"
mv "r12 L-E Cyborg Factory.tif" "Cyborg Factory.tif"
mv "r12 R-A Sensor Upgrade.tif" "Sensor Upgrade.tif"
mv "r12 R-B Automated Repair Facility.tif" "Automated Repair Facility.tif"
mv "r12 R-C Research Module.tif" "Research Module.tif"
mv "r12 R-D Repair Facility.tif" "Repair Facility.tif"
mv "r12 R-E Command Relay Post.tif" "Command Relay Post.tif"
mv "r13 L-A Reinforced Base Structure Materials.tif" "Reinforced Base Structure Materials.tif"
mv "r13 L-B Reinforced Base Structure Materials Mk3.tif" "Reinforced Base Structure Materials Mk3.tif"
mv "r13 L-C VTOL Rearming Pad.tif" "VTOL Rearming Pad.tif"
mv "r13 L-D Robotic Manufacturing.tif" "Robotic Manufacturing.tif"
mv "r13 L-E Super Transport.tif" "Super Transport.tif"
mv "r13 R-A Reinforced Base Structure Materials Mk2.tif" "Reinforced Base Structure Materials Mk2.tif"
mv "r13 R-B Automated Manufacturing.tif" "Automated Manufacturing.tif"
mv "r13 R-C VTOL Factory.tif" "VTOL Factory.tif"
mv "r13 R-D Cyborg Transport.tif" "Cyborg Transport.tif"
mv "r13 R-E Cyborg Superdense Thermal Armour.tif" "Cyborg Superdense Thermal Armour.tif"
mv "r14 L-A Cyborg Superdense Thermal Armour Mk2.tif" "Cyborg Superdense Thermal Armour Mk2.tif"
mv "r14 L-B Cyborg Composite Alloys.tif" "Cyborg Composite Alloys.tif"
mv "r14 L-C Cyborg Composite Alloys Mk3.tif" "Cyborg Composite Alloys Mk3.tif"
mv "r14 L-D Cyborg Dense Composite Alloys Mk2.tif" "Cyborg Dense Composite Alloys Mk2.tif"
mv "r14 L-E Cyborg Superdense Composite Alloys.tif" "Cyborg Superdense Composite Alloys.tif"
mv "r14 R-A Cyborg Superdense Thermal Armour Mk3.tif" "Cyborg Superdense Thermal Armour Mk3.tif"
mv "r14 R-B Cyborg Composite Alloys Mk2.tif" "Cyborg Composite Alloys Mk2.tif"
mv "r14 R-C Cyborg Dense Composite Alloys.tif" "Cyborg Dense Composite Alloys.tif"
mv "r14 R-D Cyborg Dense Composite Alloys Mk3.tif" "Cyborg Dense Composite Alloys Mk3.tif"
mv "r14 R-E Cyborg Superdense Composite Alloys Mk2.tif" "Cyborg Superdense Composite Alloys Mk2.tif"
mv "r15 L-A Cyborg Superdense Composite Alloys Mk3.tif" "Cyborg Superdense Composite Alloys Mk3.tif"
mv "r15 L-B Plasmite Flamer Bunker.tif" "Plasmite Flamer Bunker.tif"
mv "r15 L-C Hardcrete.tif" "Hardcrete.tif"
mv "r15 L-D Light Cannon Hardpoint.tif" "Light Cannon Hardpoint.tif"
mv "r15 L-E Heavy Cannon Hardpoint.tif" "Heavy Cannon Hardpoint.tif"
mv "r15 R-A Incendiary Howitzer Emplacement.tif" "Incendiary Howitzer Emplacement.tif"
mv "r15 R-B Incendiary Mortar Pit.tif" "Incendiary Mortar Pit.tif"
mv "r15 R-C Hardcrete Gate.tif" "Hardcrete Gate.tif"
mv "r15 R-D Heavy Machinegun Hardpoint.tif" "Heavy Machinegun Hardpoint.tif"
mv "r15 R-E Medium Cannon Hardpoint.tif" "Medium Cannon Hardpoint.tif"
mv "r16 L-A Improved Hardcrete.tif" "Improved Hardcrete.tif"
mv "r16 L-B Machinegun Guard Tower.tif" "Machinegun Guard Tower.tif"
mv "r16 L-C Machinegun Bunker.tif" "Machinegun Bunker.tif"
mv "r16 L-D Flamer Bunker.tif" "Flamer Bunker.tif"
mv "r16 L-E Improved Hardcrete Mk3.tif" "Improved Hardcrete Mk3.tif"
mv "r16 R-A Tank Traps.tif" "Tank Traps.tif"
mv "r16 R-B Mini-Rocket Tower.tif" "Mini-Rocket Tower.tif"
mv "r16 R-C Light Cannon Bunker.tif" "Light Cannon Bunker.tif"
mv "r16 R-D Improved Hardcrete Mk2.tif" "Improved Hardcrete Mk2.tif"
mv "r16 R-E Lancer Hardpoint.tif" "Lancer Hardpoint.tif"
mv "r17 L-A Lancer Tower.tif" "Lancer Tower.tif"
mv "r17 L-B Hurricane AA Site.tif" "Hurricane AA Site.tif"
mv "r17 L-C Flashlight Emplacement.tif" "Flashlight Emplacement.tif"
mv "r17 L-D Pepperpot Pit.tif" "Pepperpot Pit.tif"
mv "r17 L-E Needle Gun Tower.tif" "Needle Gun Tower.tif"
mv "r17 R-A AA Flak Cannon Emplacement.tif" "AA Flak Cannon Emplacement.tif"
mv "r17 R-B Whirlwind AA Site.tif" "Whirlwind AA Site.tif"
mv "r17 R-C Hellstorm Emplacement.tif" "Hellstorm Emplacement.tif"
mv "r17 R-D Scourge Missile Tower.tif" "Scourge Missile Tower.tif"
mv "r17 R-E Howitzer Emplacement.tif" "Howitzer Emplacement.tif"
mv "r18 L-A Mortar Pit.tif" "Mortar Pit.tif"
mv "r18 L-B Assault Cannon Hardpoint.tif" "Assault Cannon Hardpoint.tif"
mv "r18 L-C Rail Gun Hardpoint.tif" "Rail Gun Hardpoint.tif"
mv "r18 L-D Inferno Bunker.tif" "Inferno Bunker.tif"
mv "r18 L-E Vindicator SAM Site.tif" "Vindicator SAM Site.tif"
mv "r18 R-A Assault Gun Hardpoint.tif" "Assault Gun Hardpoint.tif"
mv "r18 R-B Pulse Laser Hardpoint.tif" "Pulse Laser Hardpoint.tif"
mv "r18 R-C Sunburst AA Site.tif" "Sunburst AA Site.tif"
mv "r18 R-D Avenger SAM Site.tif" "Avenger SAM Site.tif"
mv "r18 R-E Ground Shaker Emplacement.tif" "Ground Shaker Emplacement.tif"
mv "r19 L-A Mini-Rocket Battery.tif" "Mini-Rocket Battery.tif"
mv "r19 L-B Bombard Pit.tif" "Bombard Pit.tif"
mv "r19 L-C Tank Killer Emplacement.tif" "Tank Killer Emplacement.tif"
mv "r19 L-D Pulse Laser Tower.tif" "Pulse Laser Tower.tif"
mv "r19 L-E Gauss Cannon Emplacement.tif" "Gauss Cannon Emplacement.tif"
mv "r19 R-A Rotary MG Bunker.tif" "Rotary MG Bunker.tif"
mv "r19 R-B Ripple Rocket Battery.tif" "Ripple Rocket Battery.tif"
mv "r19 R-C Hyper Velocity Cannon Emplacement.tif" "Hyper Velocity Cannon Emplacement.tif"
mv "r19 R-D Rail Gun Emplacement.tif" "Rail Gun Emplacement.tif"
mv "r19 R-E Seraph Missile Battery.tif" "Seraph Missile Battery.tif"
mv "r20 L-A Archangel Missile Battery.tif" "Archangel Missile Battery.tif"
mv "r20 L-B Hyper Velocity Cannon Hardpoint.tif" "Hyper Velocity Cannon Hardpoint.tif"
mv "r20 L-C Supercrete.tif" "Supercrete.tif"
mv "r20 L-D Supercrete Mk3.tif" "Supercrete Mk3.tif"
mv "r20 L-E Plascrete Mk2.tif" "Plascrete Mk2.tif"
mv "r20 R-A Tank Killer Hardpoint.tif" "Tank Killer Hardpoint.tif"
mv "r20 R-B Scourge Missile Hardpoint.tif" "Scourge Missile Hardpoint.tif"
mv "r20 R-C Supercrete Mk2.tif" "Supercrete Mk2.tif"
mv "r20 R-D Plascrete.tif" "Plascrete.tif"
mv "r20 R-E Plascrete Mk3.tif" "Plascrete Mk3.tif"
mv "r21 L-A Thermal Armour.tif" "Thermal Armour.tif"
mv "r21 L-B Cluster Bomb Bay.tif" "Cluster Bomb Bay.tif"
mv "r21 L-C HEAP Mortar Shells.tif" "HEAP Mortar Shells.tif"
mv "r21 L-D Mortar Fast Loader.tif" "Mortar Fast Loader.tif"
mv "r21 L-E APDSB MG Bullets Mk3.tif" "APDSB MG Bullets Mk3.tif"
mv "r21 R-A AA HE Flak.tif" "AA HE Flak.tif"
mv "r21 R-B Superhot Flamer Gel.tif" "Superhot Flamer Gel.tif"
mv "r21 R-C HE Rockets.tif" "HE Rockets.tif"
mv "r21 R-D Mortar Targeting Computer.tif" "Mortar Targeting Computer.tif"
mv "r21 R-E Dedicated Synaptic Link Data Analysis.tif" "Dedicated Synaptic Link Data Analysis.tif"
mv "r22 L-A Turbo-Charged Engine.tif" "Turbo-Charged Engine.tif"
mv "r22 L-B AA HE Flak Mk2.tif" "AA HE Flak Mk2.tif"
mv "r22 L-C Phosphor Bomb Bay.tif" "Phosphor Bomb Bay.tif"
mv "r22 L-D Target Acquisition Artillery Shells.tif" "Target Acquisition Artillery Shells.tif"
mv "r22 L-E HEAP Mortar Shells Mk2.tif" "HEAP Mortar Shells Mk2.tif"
mv "r22 R-A Thermal Armour Mk2.tif" "Thermal Armour Mk2.tif"
mv "r22 R-B AA Ammunition Hopper.tif" "AA Ammunition Hopper.tif"
mv "r22 R-C Superhot Flamer Gel Mk2.tif" "Superhot Flamer Gel Mk2.tif"
mv "r22 R-D HE Howitzer Shells.tif" "HE Howitzer Shells.tif"
mv "r22 R-E HE Rockets Mk2.tif" "HE Rockets Mk2.tif"
mv "r23 L-A Turbo-Charged Engine Mk2.tif" "Turbo-Charged Engine Mk2.tif"
mv "r23 L-B AA HE Flak Mk3.tif" "AA HE Flak Mk3.tif"
mv "r23 L-C Thermite Bomb Bay.tif" "Thermite Bomb Bay.tif"
mv "r23 L-D Target Acquisition Artillery Shells Mk2.tif" "Target Acquisition Artillery Shells Mk2.tif"
mv "r23 L-E HEAP Mortar Shells Mk3.tif" "HEAP Mortar Shells Mk3.tif"
mv "r23 R-A Thermal Armour Mk3.tif" "Thermal Armour Mk3.tif"
mv "r23 R-B AA Ammunition Hopper Mk2.tif" "AA Ammunition Hopper Mk2.tif"
mv "r23 R-C Superhot Flamer Gel Mk3.tif" "Superhot Flamer Gel Mk3.tif"
mv "r23 R-D HE Howitzer Shells Mk2.tif" "HE Howitzer Shells Mk2.tif"
mv "r23 R-E Rocket Autoloader.tif" "Rocket Autoloader.tif"
mv "r24 L-A Turbo-Charged Engine Mk3.tif" "Turbo-Charged Engine Mk3.tif"
mv "r24 L-B AA HEAP Flak.tif" "AA HEAP Flak.tif"
mv "r24 L-C Target Prediction Artillery Shells.tif" "Target Prediction Artillery Shells.tif"
mv "r24 L-D Stabilized Rockets.tif" "Stabilized Rockets.tif"
mv "r24 L-E HE Bomb Shells.tif" "HE Bomb Shells.tif"
mv "r24 R-A High Intensity Thermal Armour.tif" "High Intensity Thermal Armour.tif"
mv "r24 R-B AA Ammunition Hopper Mk3.tif" "AA Ammunition Hopper Mk3.tif"
mv "r24 R-C HE Howitzer Shells Mk3.tif" "HE Howitzer Shells Mk3.tif"
mv "r24 R-D HE Rockets Mk3.tif" "HE Rockets Mk3.tif"
mv "r24 R-E Thermal Imaging Mortar Shells.tif" "Thermal Imaging Mortar Shells.tif"
mv "r25 L-A High Intensity Thermal Armour Mk2.tif" "High Intensity Thermal Armour Mk2.tif"
mv "r25 L-B AA Chainfeed Loader.tif" "AA Chainfeed Loader.tif"
mv "r25 L-C HEAP Howitzer Shells.tif" "HEAP Howitzer Shells.tif"
mv "r25 L-D HEAT Rocket Warhead.tif" "HEAT Rocket Warhead.tif"
mv "r25 L-E Howitzer Autoloader.tif" "Howitzer Autoloader.tif"
mv "r25 R-A AA HEAP Flak Mk2.tif" "AA HEAP Flak Mk2.tif"
mv "r25 R-B HEAP Bomb Bay.tif" "HEAP Bomb Bay.tif"
mv "r25 R-C Rocket Autoloader Mk2.tif" "Rocket Autoloader Mk2.tif"
mv "r25 R-D Improved Bomb Warhead.tif" "Improved Bomb Warhead.tif"
mv "r25 R-E Tungsten-Tipped MG Bullets.tif" "Tungsten-Tipped MG Bullets.tif"
mv "r26 L-A High Intensity Thermal Armour Mk3.tif" "High Intensity Thermal Armour Mk3.tif"
mv "r26 L-B AA Chainfeed Loader Mk2.tif" "AA Chainfeed Loader Mk2.tif"
mv "r26 L-C Rocket Autoloader Mk3.tif" "Rocket Autoloader Mk3.tif"
mv "r26 L-D HEAT Rocket Warhead Mk2.tif" "HEAT Rocket Warhead Mk2.tif"
mv "r26 L-E Howitzer Autoloader Mk2.tif" "Howitzer Autoloader Mk2.tif"
mv "r26 R-A AA HEAP Flak Mk3.tif" "AA HEAP Flak Mk3.tif"
mv "r26 R-B HEAP Howitzer Shells Mk2.tif" "HEAP Howitzer Shells Mk2.tif"
mv "r26 R-C Improved Rocket Wire Guidance.tif" "Improved Rocket Wire Guidance.tif"
mv "r26 R-D Advanced Bomb Warhead.tif" "Advanced Bomb Warhead.tif"
mv "r26 R-E Tungsten-Tipped MG Bullets Mk2.tif" "Tungsten-Tipped MG Bullets Mk2.tif"
mv "r27 L-A AA Chainfeed Loader Mk3.tif" "AA Chainfeed Loader Mk3.tif"
mv "r27 L-B HEAT Rocket Warhead Mk3.tif" "HEAT Rocket Warhead Mk3.tif"
mv "r27 L-C Howitzer Autoloader Mk3.tif" "Howitzer Autoloader Mk3.tif"
mv "r27 L-D Dedicated Synaptic Link Data Analysis Mk2.tif" "Dedicated Synaptic Link Data Analysis Mk2.tif"
mv "r27 L-E Gas Turbine Generator.tif" "Gas Turbine Generator.tif"
mv "r27 R-A HEAP Howitzer Shells Mk3.tif" "HEAP Howitzer Shells Mk3.tif"
mv "r27 R-B Rocket Laser Designator.tif" "Rocket Laser Designator.tif"
mv "r27 R-C Tungsten-Tipped MG Bullets Mk3.tif" "Tungsten-Tipped MG Bullets Mk3.tif"
mv "r27 R-D Command Turret II.tif" "Command Turret II.tif"
mv "r27 R-E Robotic Repair Facility.tif" "Robotic Repair Facility.tif"
mv "r28 L-A HESH Rocket Warhead.tif" "HESH Rocket Warhead.tif"
mv "r28 L-B Howitzer Fast Loader.tif" "Howitzer Fast Loader.tif"
mv "r28 L-C Dedicated Synaptic Link Data Analysis Mk3.tif" "Dedicated Synaptic Link Data Analysis Mk3.tif"
mv "r28 L-D Gas Turbine Generator Mk2.tif" "Gas Turbine Generator Mk2.tif"
mv "r28 L-E CB Tower.tif" "CB Tower.tif"
mv "r28 R-A Thermal Imaging Rockets.tif" "Thermal Imaging Rockets.tif"
mv "r28 R-B Twin Assault Cannon.tif" "Twin Assault Cannon.tif"
mv "r28 R-C Command Turret III.tif" "Command Turret III.tif"
mv "r28 R-D Improved Engineering.tif" "Improved Engineering.tif"
mv "r28 R-E VTOL Strike Tower.tif" "VTOL Strike Tower.tif"
mv "r29 L-A AA Thermal Imaging Sensor.tif" "AA Thermal Imaging Sensor.tif"
mv "r29 L-B Plasma Cannon.tif" "Plasma Cannon.tif"
mv "r29 L-C Gas Turbine Generator Mk3.tif" "Gas Turbine Generator Mk3.tif"
mv "r29 L-D VTOL Strike Turret.tif" "VTOL Strike Turret.tif"
mv "r29 L-E Radar Detector.tif" "Radar Detector.tif"
mv "r29 R-A HESH Rocket Warhead Mk2.tif" "HESH Rocket Warhead Mk2.tif"
mv "r29 R-B Neural Synapse Research Brain.tif" "Neural Synapse Research Brain.tif"
mv "r29 R-C CB Turret.tif" "CB Turret.tif"
mv "r29 R-D Sensor Upgrade Mk2.tif" "Sensor Upgrade Mk2.tif"
mv "r29 R-E Automated VTOL Rearming.tif" "Automated VTOL Rearming.tif"
mv "r30 L-A Gas Turbine Engine.tif" "Gas Turbine Engine.tif"
mv "r30 L-B Improved Laser Focusing.tif" "Improved Laser Focusing.tif"
mv "r30 L-C Hardened Rail Dart.tif" "Hardened Rail Dart.tif"
mv "r30 L-D Seraph Missile Array.tif" "Seraph Missile Array.tif"
mv "r30 L-E Twin Assault Gun.tif" "Twin Assault Gun.tif"
mv "r30 R-A AA Target Acquisition Shells.tif" "AA Target Acquisition Shells.tif"
mv "r30 R-B Advanced Missile Allocation System.tif" "Advanced Missile Allocation System.tif"
mv "r30 R-C HESH Rocket Warhead Mk3.tif" "HESH Rocket Warhead Mk3.tif"
mv "r30 R-D Superhot Plasmite Gel.tif" "Superhot Plasmite Gel.tif"
mv "r30 R-E Plasmite Bomb.tif" "Plasmite Bomb.tif"
mv "r31 L-A Gas Turbine Engine Mk2.tif" "Gas Turbine Engine Mk2.tif"
mv "r31 L-B Hi-Energy Laser Emitter.tif" "Hi-Energy Laser Emitter.tif"
mv "r31 L-C Advanced Missile Allocation System Mk2.tif" "Advanced Missile Allocation System Mk2.tif"
mv "r31 L-D Hardened Rail Dart Mk2.tif" "Hardened Rail Dart Mk2.tif"
mv "r31 L-E Depleted Uranium MG Bullets.tif" "Depleted Uranium MG Bullets.tif"
mv "r31 R-A AA Target Prediction Computer.tif" "AA Target Prediction Computer.tif"
mv "r31 R-B Advanced Missile Warhead.tif" "Advanced Missile Warhead.tif"
mv "r31 R-C Rail Target Prediction Computer.tif" "Rail Target Prediction Computer.tif"
mv "r31 R-D Superhot Plasmite Gel Mk2.tif" "Superhot Plasmite Gel Mk2.tif"
mv "r31 R-E Neural Synapse Research Brain Mk2.tif" "Neural Synapse Research Brain Mk2.tif"
mv "r32 L-A Gas Turbine Engine Mk3.tif" "Gas Turbine Engine Mk3.tif"
mv "r32 L-B Thermopole Energiser.tif" "Thermopole Energiser.tif"
mv "r32 L-C Advanced Missile Warhead Mk2.tif" "Advanced Missile Warhead Mk2.tif"
mv "r32 L-D Hardened Rail Dart Mk3.tif" "Hardened Rail Dart Mk3.tif"
mv "r32 L-E Target Acquisition Mortar Shells.tif" "Target Acquisition Mortar Shells.tif"
mv "r32 R-A Hi-Energy Laser Emitter Mk2.tif" "Hi-Energy Laser Emitter Mk2.tif"
mv "r32 R-B Target Prediction Missiles.tif" "Target Prediction Missiles.tif"
mv "r32 R-C Advanced Missile Allocation System Mk3.tif" "Advanced Missile Allocation System Mk3.tif"
mv "r32 R-D Rail Gun ROF.tif" "Rail Gun ROF.tif"
mv "r32 R-E Heavy Laser.tif" "Heavy Laser.tif"
mv "r33 L-A Heavy Body - Wyvern.tif" "Heavy Body - Wyvern.tif"
mv "r33 L-B Thermopole Energiser Mk2.tif" "Thermopole Energiser Mk2.tif"
mv "r33 L-C Advanced Missile Warhead Mk3.tif" "Advanced Missile Warhead Mk3.tif"
mv "r33 L-D Archangel Missile.tif" "Archangel Missile.tif"
mv "r33 L-E Stormbringer AA Laser.tif" "Stormbringer AA Laser.tif"
mv "r33 R-A Hi-Energy Laser Emitter Mk3.tif" "Hi-Energy Laser Emitter Mk3.tif"
mv "r33 R-B Search & Destroy Missiles.tif" "Search & Destroy Missiles.tif"
mv "r33 R-C Rail Gun ROF Mk2.tif" "Rail Gun ROF Mk2.tif"
mv "r33 R-D Superhot Plasmite Gel Mk3.tif" "Superhot Plasmite Gel Mk3.tif"
mv "r33 R-E Neural Synapse Research Brain Mk3.tif" "Neural Synapse Research Brain Mk3.tif"
mv "r34 L-A Multi Turret Body - Dragon.tif" "Multi Turret Body - Dragon.tif"
mv "r34 L-B Rail Gun ROF Mk3.tif" "Rail Gun ROF Mk3.tif"
mv "r34 L-C Auto-Repair.tif" "Auto-Repair.tif"
mv "r34 L-D Vapour Turbine Generator.tif" "Vapour Turbine Generator.tif"
mv "r34 L-E VTOL CB Tower.tif" "VTOL CB Tower.tif"
mv "r34 R-A Thermopole Energiser Mk3.tif" "Thermopole Energiser Mk3.tif"
mv "r34 R-B Vindicator SAM.tif" "Vindicator SAM.tif"
mv "r34 R-C Command Turret IV.tif" "Command Turret IV.tif"
mv "r34 R-D Advanced Engineering.tif" "Advanced Engineering.tif"
mv "r34 R-E Sensor Upgrade Mk3.tif" "Sensor Upgrade Mk3.tif"
mv "r35 L-A Laser Satellite Command Post.tif" "Laser Satellite Command Post.tif"
mv "r35 L-B EMP Cannon.tif" "EMP Cannon.tif"
mv "r35 L-C Nexus Resistance Circuits.tif" "Nexus Resistance Circuits.tif"
mv "r35 L-D Vapour Turbine Generator Mk3.tif" "Vapour Turbine Generator Mk3.tif"
mv "r35 L-E Advanced Repair Facility .tif" "Advanced Repair Facility .tif"
mv "r35 R-A EMP Mortar.tif" "EMP Mortar.tif"
mv "r35 R-B EMP Missile Launcher.tif" "EMP Missile Launcher.tif"
mv "r35 R-C Vapour Turbine Generator Mk2.tif" "Vapour Turbine Generator Mk2.tif"
mv "r35 R-D Whirlwind Hardpoint.tif" "Whirlwind Hardpoint.tif"
mv "r35 R-E VTOL CB Turret.tif" "VTOL CB Turret.tif"
mv "r36 L-A Wide Spectrum Sensor Tower.tif" "Wide Spectrum Sensor Tower.tif"
mv "r36 L-B Nexus Link Tower.tif" "Nexus Link Tower.tif"
mv "r36 L-C Automated VTOL Rearming Mk2.tif" "Automated VTOL Rearming Mk2.tif"
mv "r36 L-D Robotic VTOL Rearming.tif" "Robotic VTOL Rearming.tif"
mv "r36 L-E Robotic VTOL Rearming Mk3.tif" "Robotic VTOL Rearming Mk3.tif"
mv "r36 R-A Satellite Uplink Centre.tif" "Satellite Uplink Centre.tif"
mv "r36 R-B Wide Spectrum Sensor.tif" "Wide Spectrum Sensor.tif"
mv "r36 R-C Automated VTOL Rearming Mk3.tif" "Automated VTOL Rearming Mk3.tif"
mv "r36 R-D Robotic VTOL Rearming Mk2.tif" "Robotic VTOL Rearming Mk2.tif"
mv "r36 R-E Hardened Base Structure Materials.tif" "Hardened Base Structure Materials.tif"
mv "r37 L-A Hardened Base Structure Materials Mk2.tif" "Hardened Base Structure Materials Mk2.tif"
mv "r37 L-B Advanced Base Structure Materials.tif" "Advanced Base Structure Materials.tif"
mv "r37 L-C Advanced Base Structure Materials Mk3.tif" "Advanced Base Structure Materials Mk3.tif"
mv "r37 L-D Self-Replicating Manufacturing.tif" "Self-Replicating Manufacturing.tif"
mv "r37 L-E Avenger Hardpoint.tif" "Avenger Hardpoint.tif"
mv "r37 R-A Hardened Base Structure Materials Mk3.tif" "Hardened Base Structure Materials Mk3.tif"
mv "r37 R-B Advanced Base Structure Materials Mk2.tif" "Advanced Base Structure Materials Mk2.tif"
mv "r37 R-C Advanced Manufacturing.tif" "Advanced Manufacturing.tif"
mv "r37 R-D AA Flak Cannon Hardpoint.tif" "AA Flak Cannon Hardpoint.tif"
mv "r37 R-E Twin Assault Gun Hardpoint.tif" "Twin Assault Gun Hardpoint.tif"
mv "r38 L-A Super HPV Cyborg.tif" "Super HPV Cyborg.tif"
mv "r38 L-B Cyborg Thermal Armour Mk2.tif" "Cyborg Thermal Armour Mk2.tif"
mv "r38 L-C Cyborg High Intensity Thermal Armour.tif" "Cyborg High Intensity Thermal Armour.tif"
mv "r38 L-D Cyborg High Intensity Thermal Armour Mk3.tif" "Cyborg High Intensity Thermal Armour Mk3.tif"
mv "r38 L-E Super Auto-Cannon Cyborg.tif" "Super Auto-Cannon Cyborg.tif"
mv "r38 R-A Cyborg Thermal Armour.tif" "Cyborg Thermal Armour.tif"
mv "r38 R-B Cyborg Thermal Armour Mk3.tif" "Cyborg Thermal Armour Mk3.tif"
mv "r38 R-C Cyborg High Intensity Thermal Armour Mk2.tif" "Cyborg High Intensity Thermal Armour Mk2.tif"
mv "r38 R-D Cyborg Heavy-Gunner.tif" "Cyborg Heavy-Gunner.tif"
mv "r38 R-E Super Tank-Killer Cyborg.tif" "Super Tank-Killer Cyborg.tif"
mv "r39 L-A Super Pulse Laser Cyborg.tif" "Super Pulse Laser Cyborg.tif"
mv "r39 L-B Super Scourge Cyborg.tif" "Super Scourge Cyborg.tif"
mv "r39 L-C Gauss Cannon Hardpoint.tif" "Gauss Cannon Hardpoint.tif"
mv "r39 L-D Cannon Fortress.tif" "Cannon Fortress.tif"
mv "r39 L-E Heavy Laser Emplacement.tif" "Heavy Laser Emplacement.tif"
mv "r39 R-A Super Rail-Gunner.tif" "Super Rail-Gunner.tif"
mv "r39 R-B Vindicator Hardpoint.tif" "Vindicator Hardpoint.tif"
mv "r39 R-C Mass Driver Fortress.tif" "Mass Driver Fortress.tif"
mv "r39 R-D Twin Assault Cannon Bunker.tif" "Twin Assault Cannon Bunker.tif"
mv "r39 R-E Plasma Cannon Emplacement.tif" "Plasma Cannon Emplacement.tif"
mv "r40 L-A EMP Cannon Tower.tif" "EMP Cannon Tower.tif"
mv "r40 L-B Missile Fortress.tif" "Missile Fortress.tif"
mv "r40 L-C Plasteel Mk2.tif" "Plasteel Mk2.tif"
mv "r40 L-D Stormbringer Emplacement.tif" "Stormbringer Emplacement.tif"
mv "r40 R-A Heavy Rocket Bastion.tif" "Heavy Rocket Bastion.tif"
mv "r40 R-B Plasteel.tif" "Plasteel.tif"
mv "r40 R-C Plasteel Mk3.tif" "Plasteel Mk3.tif"
mv "r40 R-D EMP Mortar Pit.tif" "EMP Mortar Pit.tif"
echo -e "\e[92mConvert these files with GIMP Plugin - David's Batch Processor."
echo -e "\e[92mUse GIF format and 255 indexed colors for the output files."