#!/bin/bash
mv "s1 L-A T VTOL CB Radar Turret.tif" "T VTOL CB Radar Turret.tif"
mv "s1 L-B T Nexus Link.tif" "T Nexus Link.tif"
mv "s1 L-C T Sensor Turret.tif" "T Sensor Turret.tif"
mv "s1 L-D T Radar Detector.tif" "T Radar Detector.tif"
mv "s1 R-A T VTOL Strike Turret.tif" "T VTOL Strike Turret.tif"
mv "s1 R-B T CB Radar Turret.tif" "T CB Radar Turret.tif"
mv "s1 R-C T Wide Spectrum Sensor.tif" "T Wide Spectrum Sensor.tif"
mv "s1 R-D T Jammer Turret.tif" "T Jammer Turret.tif"
mv "s2 L-A T Truck.tif" "T Truck.tif"
mv "s2 L-B T Heavy Repair Turret.tif" "T Heavy Repair Turret.tif"
mv "s2 R-A T Repair Turret.tif" "T Repair Turret.tif"
mv "s2 R-B T Command Turret.tif" "T Command Turret.tif"
echo -e "\e[92mConvert these files with GIMP Plugin - David's Batch Processor."
echo -e "\e[92mUse GIF format and 255 indexed colors for the output files."